### ISSUE TITLE
Template label for pasting the currently opened file/selection

### ISSUE THREAD

**Issue by shalak** [carlrobertoh/CodeGPT#100]
It would be a nice improvement to be able to type something like this in chat:

```
My project gradle file look like {{this}}. How can I fix <blah, blah, blah>
```

The `{{this}}` placeholder would be replaced on-the-fly with the content of currently focused file in IDE, or currently selected part of code (if any).

I only chose `{{}}` format because o templating used in CodeGPT settings window, for better UX, we could go with `!this` format.

**Comment by carlrobertoh** [comment]
It would be a nice improvement! I think the placeholder needs to be configurable in the settings.

**Comment by shalak** [comment]
Would be great to have another placeholder (something like sub-label), that would produce a path to the file - e.g. `!this:path` and `!this+path` that would produce:

    ```
    /path/to/file:
    <file content>
    ```

(including the markdown code-block marks)

And we could go even further - to paste all files opened in current tab, e.g.

Prompting:
```
I have the following structure:
!all+path
write unit tests for all of them
```
would result in:

    I have the following file structure:
    ```
    /path/to/file1:
    <content of file1>
    
    /path/to/file2:
    <content of file2>
    ```
    write unit tests for all of them
    
I frequently find myself doing just that.

**Comment by carlrobertoh** [comment]
I ditched the placeholders idea and went with simple [Select and Ask](https://github.com/carlrobertoh/CodeGPT/blob/master/docs/assets/gif/custom-prompt.gif) logic.

Please re-open the ticket if you would like to discuss further steps.

**Comment by shalak** [comment]
I'm not sure I follow - the string `selected code` is the placeholder?

**Comment by carlrobertoh** [comment]
No placeholder is used, you need to simply highlight a code block in the main editor and ask the question, highlighted code is included in the prompt automatically.

**Comment by carlrobertoh** [comment]
Yes, the highlighted text is added after the user's prompt. You can see that if you reopen the chat tab.

**Comment by user753** [comment]
Something like {{file:path/to/file}} would be very useful. It would simply insert the content of the file into this placeholder.

For example, it could be used in actions like this: "Write tests for the selected code {{selectedCode}}, using {{file:path/to/good-test-example}} as an example."

In my experience, it improves the quality of the code.
