### ISSUE TITLE
Use Chinese input to garbled

### ISSUE THREAD

**Issue by 0xLaiHo** [carlrobertoh/CodeGPT#101]
![image](https://user-images.githubusercontent.com/18321888/235858810-83648e2d-0d25-4f95-8a6c-c3afcfee5e75.png)

**Comment by 0xLaiHo** [comment]
on windows11

**Comment by carlrobertoh** [comment]
Hi @0xLaiHo,

Is the issue still present in the latest version?

**Comment by 0xLaiHo** [comment]
Thank you for your reply, this problem has been solved in latest version
