### ISSUE TITLE
Potentially uses the wrong api for chat gpt 4

### ISSUE THREAD

**Issue by liveaffiliates** [carlrobertoh/CodeGPT#102]
This could be such a good plugin but it looks like you have setup with completions instead of chat completion so there is no history being sent. What use is it having a conversation where you can send multiple messages but it has forgotten everything you have previously said every time you send a new one. If that is all it is why have it in a chat list? Might as well be a single textbox that clears every time you use it. Not sure if this is the problem but right now its like asking a goldfish for coding advice.

<img width="282" alt="image" src="https://user-images.githubusercontent.com/15039954/236596255-59ad1027-576c-4abf-bb58-7049fe5a43d5.png">

**Comment by carlrobertoh** [comment]
Hi,

Firstly, it seems like you're either using the old version of the plugin or JCEF is not supported in your IDE Runtime. I have stopped supporting the old UI and it might contain some bugs.

Secondly, both chat and text completions have contextual support:
 
<img width="957" alt="Screenshot 2023-05-06 at 13 42 22" src="https://user-images.githubusercontent.com/15891408/236624900-abbe82c1-d37c-41e4-9839-2c1e2a53bb10.png">
<img width="738" alt="Screenshot 2023-05-06 at 13 43 03" src="https://user-images.githubusercontent.com/15891408/236624904-22509792-01ae-460a-9173-730737b7fc6e.png">

**Comment by liveaffiliates** [comment]
Thanks, I installed it yesterday on Android Studio and there are no updates available. I checked and no jcef support https://intellij-support.jetbrains.com/hc/en-us/community/posts/10430962887442-JCEF-is-not-supported-in-Android-Studio

**Comment by carlrobertoh** [comment]
@liveaffiliates You can select/install another runtime manually
https://github.com/carlrobertoh/CodeGPT/issues/94#issuecomment-1525587277
