### ISSUE TITLE
Signs of somewhat buggy operation around opening and closing tabs.

### ISSUE THREAD

**Issue by self-driven** [carlrobertoh/CodeGPT#105]
Windows 10 + IntelliJ IDE 2023.1.1 (Ultimate Edition) + CodeGPT 1.10.7

The content of the active tab disappears when another tab is closed.

The state before the error phenomenon:
2 empty tabs open, Chat1 and Chat 2.

I open a 3rd chat by highlighting a code block and selecting a prompt. Chat 3 opens normally and its content is created.
Then I close the empty Chat 2 tab, **the contents of the Chat 3 tab disappear**, but the "Regenerate response" button and the "ask me anything" prompt remain.

If I click on "open in editor", the file with the md extension opens perfectly, but the contents of the Chat tab only appear again after the IDE is restarted, but not as Chat 3, but on Chat 1.

**Comment by carlrobertoh** [comment]
Hey,

I tried replicating the above issue but without any luck.

Could you please verify if the issue also occurs with the 'Off-Screen Browser Rendering' flag turned ON? 
You can find this option under CodeGPT > Advanced Settings > Use off-screen browser rendering.

**Comment by self-driven** [comment]
Thanks, turning on the 'Off-Screen Browser Rendering' flag solved it.
