### ISSUE TITLE
Model does not exist error

### ISSUE THREAD

**Issue by jcroucher** [carlrobertoh/CodeGPT#106]
I am getting this error today 

The model: gpt-4 does not exist
The model: gpt-4-32k does not exist

Version 1.10.7
Authorised and GPTPlus Account enabled

**Comment by dragetd** [comment]
Access to gpt-4 API (what you need here) does not depend on ChatGPTPlus. You need to have explicitly gpt-4 API access enabled on OpenAI which is currently in limited beta.

Nothing this plugin can do about.

**Comment by jcroucher** [comment]
I have it enabled. It has been working up until yesterday.

**Comment by carlrobertoh** [comment]
Hey,

Please see if the `gpt-4` model is listed for your user:
```
curl https://api.openai.com/v1/models \
  -H "Authorization: Bearer $OPENAI_API_KEY"
```

**Comment by jcroucher** [comment]
Looks like my GPT-4 API access has been removed.
It's not even listed on the rate limit page anymore. I will follow up with OpenAi.
