### ISSUE TITLE
Support some actions that can directly copy or replace gpt output code

### ISSUE THREAD

**Issue by rogeryk** [carlrobertoh/CodeGPT#107]
Now, if you want to use the code generated in gpt, you have to use the mouse to click on the button on the code block. It would be easier if shortcuts were supported.

More actions can also be supported, like the one in raycast ai
<img width="584" alt="image" src="https://github.com/carlrobertoh/CodeGPT/assets/28089185/835e95a2-5c4f-4b1c-bb1e-cbf1edb39d42">

**Comment by carlrobertoh** [comment]
Thank you! I appreciate your input and will definitely consider it to improve the extension.

**Comment by chabicht** [comment]
I second this request. It also would be nice to be able to see/copy the _raw_ AI response, as the plugin sometimes misinterprets the answers.
E.g. if one asks for a markdown-formatted response and the AI generates code blocks, the markdown following the code block is converted to HTML.
![image](https://github.com/carlrobertoh/CodeGPT/assets/9286703/8fbd45c8-0c04-49b5-8edd-8145c30117bc)

**Comment by carlrobertoh** [comment]
Hi @chabicht 

The raw AI response can be seen by opening the conversation inside the editor. 
<img width="282" alt="Screen Shot 2023-07-03 at 14 17 43" src="https://github.com/carlrobertoh/CodeGPT/assets/15891408/bdf95da3-937f-48f2-822f-81ac14043569">

Furthermore, I am trying to improve the response rendering bit by bit.

**Comment by chabicht** [comment]
Thanks, that tip helps a lot! :-)
