### ISSUE TITLE
feat: diff against selected code

### ISSUE THREAD

**Issue by smuu** [carlrobertoh/CodeGPT#109]
Nice project!

It would be awesome to diff a code block against the selected code. This way one can check what's changed before replacing the content.

**Comment by carlrobertoh** [comment]
Thank you!
Even though it seems like a cool feature, it would be hard to implement because the generated code might be in chunks or the prompt could have an entirely different meaning (e.g., "Write Tests").

**Comment by BenceSzalai** [comment]
Meanwhile you can copy code from the chat, select code in the editor and do right click / Compare with clipboard.

**Comment by carlrobertoh** [comment]
Closing the issue: Diffing has already been added but needs some tweaking.
