### ISSUE TITLE
Why is it charged?

### ISSUE THREAD

**Issue by MangerLe** [carlrobertoh/CodeGPT#11]
I opened Settings and entered my apikey, but found that there was a charge for chatgpt. Isn't it free?

And is the reverse proxy used inside the plug-in?

**Comment by carlrobertoh** [comment]
Hi @MangerLe 

The Completion API isn't free, however you can start experimenting with $18 in free credit that can be used during your first 3 months. - [https://openai.com/pricing](https://openai.com/pricing)

The browser based ChatGPT is free(at the moment) and the reverse proxy is used to circumvent the Cloudflare to access that.

Best regards

**Comment by MangerLe** [comment]
Thank you very much
