### ISSUE TITLE
The chat doesn't remember the conversation context

### ISSUE THREAD

**Issue by ultraon** [carlrobertoh/CodeGPT#112]
Plugin version - 1.10.8

When I ask a question and it returns the response, the next question can't reference the previous response.

I tried GPT-3.5 (turbo) and GPT-4 models.

![Screenshot 2023-05-22 at 18 19 28](https://github.com/carlrobertoh/CodeGPT/assets/6382537/1f22fa2b-07f5-40f8-baa3-0ab837122bc8)

So, the issue breaks the different `chat tabs` functionality, it just doesn't make any sense.

**Comment by carlrobertoh** [comment]
Hi,

Seems like JCEF is not supported in your IDE runtime. I have stopped supporting the older UI which might contain several bugs, including how the conversation context is put together.

Please follow these steps [provided here](https://github.com/carlrobertoh/CodeGPT/issues/94#issuecomment-1525587277).

**Comment by ultraon** [comment]
@carlrobertoh Thank you so much, now it works.
Just some details for others who want to understand how to fix the issue:
- `JCEF` is a feature present in JetBrains IDEs, like IntelliJ IDEA and WebStorm, allowing them to display web content within the IDE using Chromium-based browser components (the answer is from ChatGPT-4).
- how to choose JCEF-based Java runtime for the IDE see https://issuetracker.google.com/issues/159933628#comment19
<img width="1412" alt="Screenshot 2023-05-22 at 20 08 36" src="https://github.com/carlrobertoh/CodeGPT/assets/6382537/965649a7-c6fa-4952-b929-31cc1e7b9603">

**Comment by ultraon** [comment]
I believe the issue can be closed as solved.

**Comment by carlrobertoh** [comment]
Glad you got it worked out!

Probably should create a FAQ section to readme.
