### ISSUE TITLE
CodeGPT steals focus from the editor

### ISSUE THREAD

**Issue by reubenfirmin** [carlrobertoh/CodeGPT#113]
When trying to copy and paste from the response, there's a path for the focus to be stolen by the CodeGPT sidebar which prevents editing in the editor. Workaround is to switch to another sidebar and then back.

**Comment by carlrobertoh** [comment]
@reubenfirmin @jerzydziewierz 
Could you try upgrading the extension to the latest version and see if the problem still exists?
Thank you.
