### ISSUE TITLE
The textarea is too small. It should be strechable , or even grow with the text until a limit

### ISSUE THREAD

**Issue by lucashpacheco** [carlrobertoh/CodeGPT#114]
The textarea is too small. It should be strechable , or even grow with the text until a limit. 

I tryed to create an solution for this , but i dont know java , so i cant build the project well , until at master branch , tests were broken. 

Possible solution `ee/carlrobert/codegpt/toolwindow/components/TextArea.java` :

```
public TextArea(Runnable onSubmit) {
  super();
  getEmptyText().setText("Ask me anything...");
  setMargin(JBUI.insets(5));
  addSubmitButton(onSubmit);
  addShiftEnterInputMap(this, onSubmit);

  JScrollPane scrollPane = new JScrollPane(this);
  scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
  scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
  
  // Set the preferred size so that the text area is initially visible
  scrollPane.setPreferredSize(new Dimension(200, 200));
}
```

**Comment by carlrobertoh** [comment]
Sorry for the delayed reply.

I will try to find a solution for this. The text area should grow automatically, instead of hard-coding the height.

**Comment by carlrobertoh** [comment]
Closing this issue.

The height of the text area will grow according to the content (v2.0.0).
Unfortunately I didn't set any limit, will do that in another release.
