### ISSUE TITLE
Problems with getting the focus in and out of the chat box

### ISSUE THREAD

**Issue by jerzydziewierz** [carlrobertoh/CodeGPT#116]
# Problem 1

the chat box sometimes doesn't receive focus on the first click, making me randomly click around until it begins to work,

then,

after using the "replace section" button, the focus again does not return to the main editor "not automatically" but even after clicking several times. It only gets unstuck after randomly clicking around on various items. 

### Action:

Ubuntu 20, CLion, 
install the plug-in, 
then open the chat tab
click on the text entry below the output window in the CodeGPT tab

### Expected result 

the cursor appears in the "Ask me anything" box, and it accepts keystrokes

### Actual result

The focus does not enter there, keystrokes land either nowhere, or worse! into the main code editor. 

### Workaround

 click around, open a second chat tab. Then, the second chat tab finally accepts a question.

**Comment by jerzydziewierz** [comment]
# Problem 2

Moreover, this is not the end.

The chat response box sometimes does not show the content, at all

### Action

get to enter some text into the box
press enter

### Expected result

Response from GPT-4 appears

### Actual result

It appears that something is happening, the "empty content" is scrolling, but the actual response text is plain invisible

### Workaround

Open another chat window using the + button. In there, things appear to work correctly.




Finally, I get

**Comment by jerzydziewierz** [comment]
# Problem 3

Going back to the main editor is also problematic

**Comment by carlrobertoh** [comment]
Hi, thank you for reporting.

I will try to go over these bugs as soon as possible. Early next week, I'm going to release a major version that might solve a couple of these.

**Comment by carlrobertoh** [comment]
@jerzydziewierz 
Could you try upgrading the extension to the latest version and see if these problems still exists?
