### ISSUE TITLE
Documentation - Azure OpenAI

### ISSUE THREAD

**Issue by mborgraevetalan** [carlrobertoh/CodeGPT#119]
Hi,
I can't find the proper inputs to fill in the Azure OpenAI information to use with this plugin, i keep getting `Resource not found` errors. I suspect i'm not putting the ids and names at the proper place, or the API key header is not matching Azure OpenAI requirements.

Could you please help fix that (we can debug together) and possibly update the documentation so everyone else's can do it on their own ?

Also, it could be very usefull to have a "test" button in the settings window so we can trial-and-error faster.

Thanks a lot for your work !

For more technical details, I can execute this call and get an answer (replacing the `resource-name`, `deployment-id`, `version` and `API_KEY` placeholders of course). I used them in the UI window, but keep getting the `Resource not found` message as a response.
```curl "https://resource-name.openai.azure.com/openai/deployments/deployment-id/completions?api-version=version" -H "api-key: MY_API_KEY" -H "Content-Type: application/json" -d "{\"prompt\": \"Once upon a time\",\"max_tokens\": 5}"```

Matt

**Comment by mborgraeve** [comment]
Nevermind, I found the solution and documented it in https://github.com/carlrobertoh/CodeGPT/pull/120.
