### ISSUE TITLE
add a proxy setting 

### ISSUE THREAD

**Issue by qlaall** [carlrobertoh/CodeGPT#12]
Because GFW started to ban it on March 2, we need to use a socks proxy to access the chatGPT domain name, so can we add a proxy setting on the settings page so that the plug-in can access the chatGPT domain name through the socks5 proxy

**Comment by carlrobertoh** [comment]
Hi @qlaall 

Thanks for filing an issue.

I will add the proxy support in the upcoming days.

Best regards
