### ISSUE TITLE
Can not use CodeGPT while I have configured the API Key

### ISSUE THREAD

**Issue by JackieCYX** [carlrobertoh/CodeGPT#121]
While I have configured the API Key, but still do not use the plugin

**Comment by carlrobertoh** [comment]
Hi, did you experience the issue after the upgrade? You could try deleting the settings file to see if it makes any difference.

**Comment by JackieCYX** [comment]
I have upgraded the Plugin to v2.0.0，but when I use the plugin, it replies "Something went wrong. Please try again later."

**Comment by carlrobertoh** [comment]
Hi, sorry for the late reply. Did you manage to get it resolved?

**Comment by carlrobertoh** [comment]
Closing this due to lack of recent activity

**Comment by JackieCYX** [comment]
Sorry for forgetting to reply you. I will test whether the plug-in can be used normally as soon as possible.
