### ISSUE TITLE
The code is not formatted, but the actual returned code is formatted. However, it is not displayed in a formatted way.

### ISSUE THREAD

**Issue by benlan96** [carlrobertoh/CodeGPT#122]
![1686032093266](https://github.com/carlrobertoh/CodeGPT/assets/99393744/9967e3b3-ed4f-4c40-92cc-e42683aefec6)

The code is not formatted, but the actual returned code is formatted. However, it is not displayed in a formatted way.

**Comment by carlrobertoh** [comment]
Hi, could you try upgrading the plugin to the latest version(2.0.0) and see if the problem still exists?

**Comment by benlan96** [comment]
where i can get latest version(2.0.0) source code thank you

**Comment by carlrobertoh** [comment]
The source code for v2.0.0 isn't available at the moment.

The latest version can be found [here](https://plugins.jetbrains.com/plugin/21056-codegpt/versions).
