### ISSUE TITLE
CodeGPT always inputs thousands of new lines after code sample, making it unusable for me

### ISSUE THREAD

**Issue by iledan-karl** [carlrobertoh/CodeGPT#125]
https://github.com/carlrobertoh/CodeGPT/assets/21364781/7883594c-fb71-4a98-9872-6fb4f3d77831

It happens wherever I place the CodeGPT tab, even if floating or windowed.
It happens regardless if the new UI is enabled or not.
![image](https://github.com/carlrobertoh/CodeGPT/assets/21364781/ac89a12e-109c-4da2-ac5e-3abbe5e67554)

WebStorm version is 2023.1.2

**Comment by carlrobertoh** [comment]
Hi, thanks for reporting. Unfortunately, I'm off for a week and cannot investigate the issue at the moment.

If the extension is that unbearable to use, I'd suggest using the older version, which can be downloaded here: https://github.com/carlrobertoh/CodeGPT/releases/tag/1.10.8

**Comment by iledan-karl** [comment]
> Hi, thanks for reporting. Unfortunately, I'm off for a week and cannot investigate the issue at the moment.
> 
> If the extension is that unbearable to use, I'd suggest using the older version, which can be downloaded here: https://github.com/carlrobertoh/CodeGPT/releases/tag/1.10.8

That version works perfectly for me, thanks. Will be happy to provide more details to help in the investigation.

**Comment by carlrobertoh** [comment]
Hi

Do you have "Show virtual space at the bottom of the file" turned ON by any chance?
I was able to reproduce a similar issue with this setting turned on.

<img width="445" alt="Screenshot 2023-06-24 at 10 21 20" src="https://github.com/carlrobertoh/CodeGPT/assets/15891408/705068d4-d4b4-4177-981e-b3c55d695fff">

**Comment by iledan-karl** [comment]
Hi,

You are right. The issue goes away when I turn _virtual space_ off, retroactively with previous chats even. 😃

**Comment by carlrobertoh** [comment]
The bug has fixed in [v2.0.4](https://plugins.jetbrains.com/plugin/21056-codegpt/versions/stable/353051).
