### ISSUE TITLE
[BUG] No API key saved

### ISSUE THREAD

**Issue by LaurentOngaro** [carlrobertoh/CodeGPT#127]
I've just installed the 2.0.0 version and even if I've put a new API key in the plugins settings, each time I restart Pycharm, the Key is empty.
I presume It's caused by the new secured password saving process.

This issue was not present in 1.10.8

I can't use codeGPT any more with the last version ;-)

**Comment by LaurentOngaro** [comment]
Note that I have reinstalled the previous version and my api key is saved again and I can use the plugin ... great !

FYI, I don't use the "secure passwords" feature in pycharm

**Comment by LaurentOngaro** [comment]
this issue is also present in the 1.11.0 version.

**Comment by carlrobertoh** [comment]
Hi @LaurentOngaro,

Unfortunately I'm off until next week and I can't investigate the issue at the moment.

However, few things you could check:

- check if you haven't overridden the default password storage behaviour via Settings | Appearance & Behavior | System Settings | Passwords

- see what happens with the stored key (`CodeGPT - OPENAI_API_KEY`) after closing the IDE. The storage format depends on your OS, more info [here](https://plugins.jetbrains.com/docs/intellij/persisting-sensitive-data.html).

From v1.11.0, the api key persistance logic was changed.

**Comment by LaurentOngaro** [comment]
To solve this problem, I had to activate the save password function. 
Otherwise, the API key is not saved at all
So for me that's solved, but I'm not sure everyone does it or even agrees with the mandatory use of the save password feature

**Comment by carlrobertoh** [comment]
Storing the unencrypted API key in the settings state is not recommended approach and could be publicly exposed. Therefore, I am unsure of how to proceed. Using environment variables is not an option since the plugin cannot access them.

**Comment by carlrobertoh** [comment]
Closing this for now. However, this might require some documentation to be written, though.
