### ISSUE TITLE
Incompatible with mitmproxy

### ISSUE THREAD

**Issue by HXLeifeng** [carlrobertoh/CodeGPT#128]
First, thank you for this amazing tool!

I tried to switch my proxy service to mitmproxy recently, but the tool always shows "something went wrong".  Mitmproxy shows "handshake failed" and "the client does not trust the certificate".

I have installed mitmproxy's certificate, and several other similar pulgins on the market works properly. 

How can I fix this problem?

**Comment by carlrobertoh** [comment]
Hi,

I believe the underlying OkHttp client needs to be configured to trust all certificates. However, I can only investigate it sometime during next week.

In the meanwhile, you could set up a reverse proxy and configure the custom service in CodeGPT settings.

Btw, how did you install the mitmproxy certificate?

**Comment by carlrobertoh** [comment]
Hi,

Please try upgrading to the latest version to see if the problem persists.
https://plugins.jetbrains.com/plugin/21056-codegpt/versions/stable/348034

Thank you!
