### ISSUE TITLE
Reset Chat 1

### ISSUE THREAD

**Issue by egils-mtx** [carlrobertoh/CodeGPT#138]
Hey, thanks for a great plugin!
Would be really nice to have a button to reset Chat 1 since it can not be deleted and reaches limit sooner or later.
Then the only possibility to "reset" it is by manually deleting all messages.

**Comment by GiGurra** [comment]
yes please :)

**Comment by carlrobertoh** [comment]
Hi, thank you for the feature request. 
I have actually been thinking about it as well. 
The feature will be available sometime early next week.

**Comment by carlrobertoh** [comment]
Feature is available from [v2.0.3](https://plugins.jetbrains.com/plugin/21056-codegpt/versions/stable/350384).
