### ISSUE TITLE
Feature Request: Feedback to editor with diff view

### ISSUE THREAD

**Issue by GiGurra** [carlrobertoh/CodeGPT#140]
Right now we can attach code to our discussions with the current selection. This is very useful.

However what is not super practical yet is to feed the output back into code.
Sure I can copy the code manually with a few mouse and keyboard clicks, and then open my git diff view, but it is not ideal imo.

What if we could identify the code output from the AI chat, add a button next to it where it automatically opens the jetbrains diff viewer (the one used for regular diffing, e.g. git diffs). Then we could for example "please refactor this code <selection>" -> open diff view -> accept or modify etc.

Do you have any discord or similar? Maybe you could delegate some work if you feel like it's becoming too much for you alone

**Comment by siilats** [comment]
We just released the diff from someones pull request, thank you very much! Its a new button on the chat toolbar
