### ISSUE TITLE
Reintroduce custom prompt

### ISSUE THREAD

**Issue by henryruhs** [carlrobertoh/CodeGPT#144]
I highly recommend to reintroduce the custom prompt entry to the menu as "marking code" and then "writing in the chat" is a bad user experience and does not explain itself. Without reading related GitHub issues that you chanced the concept, there is no chance I would have figured this out.

**Comment by carlrobertoh** [comment]
Thank you for pointing it out!

I'll add the option back to the editor context menu.

**Comment by henryruhs** [comment]
Thanks a lot... I love your plugin. Keep on the good work.

**Comment by carlrobertoh** [comment]
@Jarrodsz This seems duplicate of https://github.com/carlrobertoh/CodeGPT/issues/100

**Comment by henryruhs** [comment]
@Jarrodsz I consider this a rude behaviour to hijack someone else issue - stop doing this!
