### ISSUE TITLE
Heavy UI error

### ISSUE THREAD

**Issue by senys** [carlrobertoh/CodeGPT#147]
I've got a heavy UI error.
The window scrolls abnormally and the content cannot be read properly.

# video
https://file.io/RtTCUETvtFiE

# envs
code gpt v2.0.3
Win11 
GoLand 2023.1.3

**Comment by carlrobertoh** [comment]
Hi

Do you have "Show virtual space at the bottom of the file" turned ON by any chance?
<img width="445" alt="Screenshot 2023-06-24 at 10 21 20" src="https://github.com/carlrobertoh/CodeGPT/assets/15891408/7cffb6ed-6b91-4735-9657-3f414a92b958">

**Comment by senys** [comment]
I don't remember doing it myself, but that option was turned on. When I turned it off, worked correctly. Thank you.

**Comment by carlrobertoh** [comment]
I'll try to fix it properly in the next release. 
Thank you for reporting!
