### ISSUE TITLE
Supports menu with directory levels and shortcut key settings 

### ISSUE THREAD

**Issue by lyrl** [carlrobertoh/CodeGPT#148]
Support menu with directory levels and the ability to set shortcuts. If it is for specific operations, there will be many settings available.

expected: 
![image](https://github.com/carlrobertoh/CodeGPT/assets/1203738/77854e44-053b-45ba-a770-299a070ba3bd)

![image](https://github.com/carlrobertoh/CodeGPT/assets/1203738/d0d4c1ab-5686-4177-b200-81073e8c269d)

Just like the tool windows menu in the first image, you can set a separate shortcut key to display all available prompts when pressed.

**Comment by carlrobertoh** [comment]
Thank you!
I'll add it to my bucket list.

**Comment by carlrobertoh** [comment]
Registered most of the tool window actions which can be assigned in the keymap. However, at the moment I couldn't find an easy way to group them inside the folders. I will look into it later.
