### ISSUE TITLE
What is the response body for custom service?

### ISSUE THREAD

**Issue by NGdust** [carlrobertoh/CodeGPT#150]
I'm trying to write my local service, but I don't know what format the response should be. I always get `Unknown API response. Code: 200, Body:`

**Comment by carlrobertoh** [comment]
Hi
The plugin depends on the [https://github.com/carlrobertoh/openai-client](openai-client) lib which is using the OpenAI API request/response model.

https://platform.openai.com/docs/api-reference/chat/create

**Comment by carlrobertoh** [comment]
Hi
The plugin depends on the [https://github.com/carlrobertoh/openai-client](openai-client) lib which is using the OpenAI API request/response model.

https://platform.openai.com/docs/api-reference/chat/create

**Comment by carlrobertoh** [comment]
Hi
The plugin depends on the [openai-client](https://github.com/carlrobertoh/openai-client) lib which is using the OpenAI API request/response model.

https://platform.openai.com/docs/api-reference/chat/create
