### ISSUE TITLE
API key not saved

### ISSUE THREAD

**Issue by dotpanic** [carlrobertoh/CodeGPT#151]
Hey!

I have a problem with the API key: I need to put it in the settings every time I start IntelliJ. Any other setting is saved just fine (i.e. Display Name).

I tried with latests versions of IntelliJ Ultimate (2023.1.3) and IntelliJ EAP (2023.2 EAP 6) but problem occurs on each version.

Plugin version 2.0.4 used.

**Comment by carlrobertoh** [comment]
Hey!

Please check that you have not selected this option:
<img width="634" alt="Screen Shot 2023-06-28 at 12 22 00" src="https://github.com/carlrobertoh/CodeGPT/assets/15891408/87f2ffe5-6300-46d1-b457-ab1fe0b71c75">

**Comment by dotpanic** [comment]
That was the problem, thank you! Have a great day Carl :)
