### ISSUE TITLE
Feature request: add temperature to plugin settings.

### ISSUE THREAD

**Issue by fantom0005** [carlrobertoh/CodeGPT#152]
Please implement the ability to modify the temperature setting when calling the OpenAI API for ChatGPT. The default temperature is set to 1, but there are instances when it's necessary to reduce the variability in ChatGPT responses. To achieve this, one needs to lower the temperature setting.

https://platform.openai.com/docs/api-reference/introduction

**Comment by carlrobertoh** [comment]
This has been on my bucket list for some time now. I will try to implement the request parameter overriding asap; it shouldn't be a huge change.

**Comment by carlrobertoh** [comment]
Support for overriding request params is now available in the latest version.
