### ISSUE TITLE
Request for feature

### ISSUE THREAD

**Issue by levitastech** [carlrobertoh/CodeGPT#153]
Hi

I would like to post a suggestion to implement a new feature in codeGpt

It will be great if you add the possibility to use local hosted model like Gpt4All instead of the openai chatGpt.

Thank you for your efforts.
Regards

**Comment by carlrobertoh** [comment]
Hi

This is already available by using the custom service option in the settings. 
<img width="635" alt="Screen Shot 2023-07-03 at 14 26 35" src="https://github.com/carlrobertoh/CodeGPT/assets/15891408/948e40db-6d16-4cb5-9f96-a4fe6dea7778">

To run custom LLMs locally, use [LocalAI](https://github.com/go-skynet/LocalAI).

**Comment by levitastech** [comment]
Hi
Thanks for your reply

Yes i did try this but didn't work.
It seems that it continues to bind to openai chat

I will try again following your instructions.

Regards

Reda Medani

Le lun. 3 juil. 2023, 14:28, Carl-Robert ***@***.***> a
écrit :

**Comment by carlrobertoh** [comment]
Hi,

I wasn't able to reproduce the issue in the latest version. For me, it binds perfectly to the custom service.

**Comment by rgrizzell** [comment]
> Hi
> 
> This is already available by using the custom service option in the settings. <img alt="Screen Shot 2023-07-03 at 14 26 35" width="635" src="https://user-images.githubusercontent.com/15891408/250569717-948e40db-6d16-4cb5-9f96-a4fe6dea7778.png">
> 
> To run custom LLMs locally, use [LocalAI](https://github.com/go-skynet/LocalAI).

Is this functionality still present in the plugin? I wish to use a local LLM.

**Comment by carlrobertoh** [comment]
Closing this issue: The plugin supports LLaMA C/C++ Port integration, allowing you to run models locally.
