### ISSUE TITLE
Feature request: Make it visible what code is shared

### ISSUE THREAD

**Issue by BenceSzalai** [carlrobertoh/CodeGPT#162]
Hi!

Thanks for the great plugin indeed, also the improvements you did reg. my previous ticket #99.

I am coming with another usability request.

At some point during my sessions I've realised that ChatGPT responded in ways that was "suspiciously" specific to my code while my prompt was generic. I started to do some tests and found out that part of my code was shared with the AI.

Now this is perfectly fine and indeed there's a feature that selected code is shared. Probably i had some bits selected during the chat.

However I don't know what code will be shared with the AI? - Code selected when I start writing my prompt or code selected when I hit the send button?

Not sure about others, but while writing prompts I usually copy paste keywords or fragments from my editor. So at the end of the day not knowing exactly what other code is added to the prompt makes the situation kind of working blind.

I would really like to see the communication with the API "as it is" without the plugin adding code fragments to my prompts and hiding those in the chat UI. It makes working with the AI very confusing. Also it is easy to accidentally start writing to the chat while something is selected in the editor.

Probably showing the included code in full may bloat the interface a bit, but Id happily accept that in exchange for clarity. If there was an option to "not hide anything". We are developers after all. We don't really expect the reality to be hidden from our eyes.

Also there should be a way to see when code is shared or about to be shared. Like an icon indicating that the next message would include some automatically added code segment, so at least I'd be aware that : Oh, snap, I started chat with something selected. Also a remove option before sending the message, so I could initiate/maintain generic chat instead of some unknown code fragments polluting the discussion.

You get what I mean I'm sure.

Also it may be problematic with huge code segments selected it may consume lots of tokens by accident...

Hope you can consider this. I assume many other devs would more like to see the chat interaction in full rather than some unknown code additions in the context we are not aware of.

**Comment by carlrobertoh** [comment]
Hey @BenceSzalai!

Thank you for the feedback!

I believe this behaviour should be configurable. Personally, I feel that the selected code will clutter the tool window, making it difficult to find the questions I was trying to ask previously. To view the previous context, you can reopen the tab.

I will try to fix it in the next release.

**Comment by BenceSzalai** [comment]
> I believe this behaviour should be configurable.

Sure. I don't want to suggest changes that would break other user's expectations or established workflow.

**Comment by carlrobertoh** [comment]
This functionality is now available from v2.2.3.

**Comment by BenceSzalai** [comment]
Thanks, cannot wait to see!

**Comment by BenceSzalai** [comment]
This is perfect, very nice work! Thank you! You are spoiling us! :)

**Comment by carlrobertoh** [comment]
Thank you! 🙂
