### ISSUE TITLE
In Version 2.0.5,Close/open any plugin, the editor actions of the plugin will be reset.

### ISSUE THREAD

**Issue by anduinnn** [carlrobertoh/CodeGPT#163]
Here is the reproduction process

![1](https://github.com/carlrobertoh/CodeGPT/assets/68073009/81c936b4-5a36-469c-8803-d0f45eb913ec)
![2](https://github.com/carlrobertoh/CodeGPT/assets/68073009/47949df6-bbce-497a-a0c1-08a9d069ad2b)
![3](https://github.com/carlrobertoh/CodeGPT/assets/68073009/15204bf2-df58-4193-988c-d3cad77f3178)

**Comment by carlrobertoh** [comment]
I'm not sure what's happening here. Do the settings reset after the IDE is restarted?

**Comment by anduinnn** [comment]
When opening or closing the plugin and restarting it
