### ISSUE TITLE
Plugin doesn't respond

### ISSUE THREAD

**Issue by mataruev** [carlrobertoh/CodeGPT#164]
Thank you for good work! I used plagin for a week on Pycharm and Rider IDEs.
It's worked fine but now stop working  on Pycharm. It's happens after tokens limit alert was show.
Now i can't change anything in plugin configuration (Ok Button is not active) and there is no respose on chat.
On Rider plugin working fine.
Pycharm shows three errors:
[Pycharm Errors.txt](https://github.com/carlrobertoh/CodeGPT/files/12145497/Pycharm.Errors.txt)

**Comment by carlrobertoh** [comment]
Weird... I will try to reproduce it locally. 
Meanwhile, you could try deleting the CodeGPT settings file (`CodeGPTSettings_170.xml`) to see if it makes any difference.

https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs

**Comment by mataruev** [comment]
Thank you very much! It's working now!

**Comment by mataruev** [comment]
Thanks!!
