### ISSUE TITLE
Auto-scroll UX bug

### ISSUE THREAD

**Issue by pokrovskyy** [carlrobertoh/CodeGPT#165]
Currently, as the ChatGPT API produces output, the window continuously auto-scrolls to the bottom. This may be fine when you are casually reading etc. but it's annoying when you want to focus on the first part of the output which keeps running away until the whole response is printed out. 

I suggest the auto-scroll is automatically disabled when you scroll away from the bottom. This way, you can focus on the first part of the output while it continues generation. Thank you!

**Comment by carlrobertoh** [comment]
Hi @pokrovskyy 

Thank you for the feedback! I will try to fix it in the upcoming release.

**Comment by BenceSzalai** [comment]
FYI: Related to #459, but the suggestion in this issue is probably better then a checkbox hidden in the config.

**Comment by carlrobertoh** [comment]
Will be fixed in the next release.
