### ISSUE TITLE
Enable custom hostname for Azure OpenAI service

### ISSUE THREAD

**Issue by Perl99** [carlrobertoh/CodeGPT#168]
My company has set up a proxy for the *.openai.azure.com. Please provide a way to override the hardcoded base url (in openai-client), so that I can use "Azure OpenAI service" for connection.
I already checked that replacing the host in the _application.properties_ resolves this, but it would be better to be able to set up it on the UI.

Thank you for this plugin

**Comment by klauern** [comment]
Same. We don't use Azure, but the process would be the same.  I asked for similar functionality in https://github.com/jupyterlab/jupyter-ai/pull/322 and https://github.com/simonw/llm/issues/139, but I think there are conventions that could be used here to make this interoperable.

**Comment by carlrobertoh** [comment]
Hi, sorry for the late reply. 
I will add support for configuring the base host in the upcoming days.

**Comment by carlrobertoh** [comment]
Ability to configure custom hostname is now available in version 2.0.6. 
Please re-open the issue if something isn't working properly.

**Comment by klauern** [comment]
I can't seem to click "OK" once I edit the settings.  I'm not sure why, but it just won't apply or change them.  It only happens when I make changes in the CodeGPT plugin
