### ISSUE TITLE
Escape character in GPT response is swallowed by the Markdown renderer

### ISSUE THREAD

**Issue by BenceSzalai** [carlrobertoh/CodeGPT#169]
Basically when ChatGPT writes a code segment and it tries to use escape characters in it, e.g. for a RegEx, it get lost  while the API response is rendered.

An image tells it better:

![CleanShot 2023-07-31 at 13 52 50](https://github.com/carlrobertoh/CodeGPT/assets/14061916/a6444d22-2b9e-45f8-8ecc-10b7eebba100)

**Comment by efstathiosntonas** [comment]
same happens for this: 

.replace(/\//g, '-');

converts to this in markdown: 

.replace(///g, '-');

**Comment by mehanoid** [comment]
I have also noticed many times that CodeGPT gives invalid regular expressions. And when you fix them, it rewrites them to invalid ones again.

**Comment by BenceSzalai** [comment]
Meanwhile as a workaround the original response can be accessed with the [Open in Editor] button on the top toolbar. Still very inconvenient.

**Comment by carlrobertoh** [comment]
This will be fixed in the next release. I'm not yet entirely sure why it was added in the first place.
