### ISSUE TITLE
Support for Alternative OpenAI GPT Models

### ISSUE THREAD

**Issue by fantom0005** [carlrobertoh/CodeGPT#170]
With the frequent updates and changes to OpenAI models, the behavior of prompts can vary significantly between different model versions. 

For instance, distinct differences have been noticed with the latest GPT-4-0313 model. To ensure consistent and expected behavior, it is proposed to add support for alternative GPT models, including the ability to fix the model version.

<img width="259" alt="image" src="https://github.com/carlrobertoh/CodeGPT/assets/3921689/f24e83b4-fd6d-4951-8c21-b85f2f76e70a">

Thank you

**Comment by JaredEzz** [comment]
On inspection of the source code, this plugin pulls available models from this library. You may want to raise this issue there. https://github.com/carlrobertoh/openai-client

That said, it seems trivial to add a "List Available Models" button that would call the `https://api.openai.com/v1/models` endpoint with the provided API key and populate the dropdown with the results

**Comment by carlrobertoh** [comment]
Version 2.4.0 now provides the option to configure custom OpenAI-compatible services, including the support for specifying a custom model.

<img width="722" alt="Screenshot 2024-02-26 at 16 00 56" src="https://github.com/carlrobertoh/CodeGPT/assets/15891408/0376b132-afd9-49f7-92e1-3b0124cf0813">

Unfortunately, a button for fetching all the available models is currently not on the roadmap.
