### ISSUE TITLE
Could I change the client timeout?

### ISSUE THREAD

**Issue by MemoryMarco** [carlrobertoh/CodeGPT#171]
I am currently using  Custom service to filter incoming requests. However, I have encountered an issue where each request must be returned within 5 seconds. Unfortunately, this constraint is not suitable for our needs because our request processing involves certain tasks, such as searching the database, which typically takes around 7 or 8 seconds. As a result, errors occur when using this plugin.

I was wondering if it would be possible for you to make the timeout parameter adjustable so that we can configure it according to our requirements. This flexibility would greatly assist us in effectively processing the requests. Thank you for considering this request; it would be of immense help to us. Thank you.

**Comment by carlrobertoh** [comment]
Hi, sorry for the late reply. 
I will add support for configuring the connect/read timeout in the upcoming days.

**Comment by MemoryMarco** [comment]
Thanks a lot!
