### ISSUE TITLE
Feature Request: Close all chats

### ISSUE THREAD

**Issue by JaredEzz** [carlrobertoh/CodeGPT#172]
I can't be the only one that uses this often enough to run into this fairly regularly:

<img width="317" alt="image" src="https://github.com/carlrobertoh/CodeGPT/assets/13698465/7f5f8305-9774-43a6-a7e4-7d5ef9725098">

It would be great to have a button near the top that simply closes all these instead of clicking "X" on each

**Comment by carlrobertoh** [comment]
I will be adding two new popup actions ("Close" and "Close Other Tabs") in the upcoming days.

<img width="341" alt="Screenshot 2023-08-21 at 23 32 54" src="https://github.com/carlrobertoh/CodeGPT/assets/15891408/a37db6dd-4453-4548-ac23-a873df41b24f">

**Comment by carlrobertoh** [comment]
Available in version 2.0.6.
