### ISSUE TITLE
Line wrap breaks words

### ISSUE THREAD

**Issue by tadamcz** [carlrobertoh/CodeGPT#174]
e.g. here the word "using" is split on two lines:

<img width="787" alt="image" src="https://github.com/carlrobertoh/CodeGPT/assets/43300673/c1b26f8a-415b-4f2a-97f7-ca3a283d87af">

**Comment by siilats** [comment]
We have some You.com sponsor money so $20 and a badge of thanks if someone would like to propose a pull request on this!
