### ISSUE TITLE
Rider added CodeGPT 1.2.1 exception

### ISSUE THREAD

**Issue by dickens1998** [carlrobertoh/CodeGPT#18]
Rider added CodeGPT 1.2.1 configured the corresponding key, but no response was returned. What happened  
![image](https://user-images.githubusercontent.com/61829821/222864259-56dcb250-52a0-440b-a91f-6b5f01c3fd9e.png)

**Comment by dickens1998** [comment]
![image](https://user-images.githubusercontent.com/61829821/222864332-5a2ca6f9-cc0c-4230-ae1d-ebb13912b802.png)

**Comment by dickens1998** [comment]
This is my current setting 
![image](https://user-images.githubusercontent.com/61829821/222868154-1c06fbfc-2884-4b6a-a64b-958c82905ba9.png)

**Comment by qlaall** [comment]
因为chatGPT的api前天被墙了 我提了issue 增加一个proxy设置。
 https://github.com/carlrobertoh/CodeGPT/issues/12

**Comment by carlrobertoh** [comment]
@qlaall @dickens1998 

Closing this as complete, let me know if you experience any issues.
