### ISSUE TITLE
Wrong pycharm window used

### ISSUE THREAD

**Issue by twidi** [carlrobertoh/CodeGPT#194]
### What happened?

If we have many projects opened in many pycharm windows, all the chat happen in the first window with CodeGPT opened.

Like if I select code for explanation in window2, the answer is added in the current chat opened in window1, regardless of the CodeGPT tool window opened in window2.

### CodeGPT version

2.0.6

### Operating System

Linux

**Comment by dguerizec** [comment]
It has the same problem in Clion.
However, it doesn't cross the editor type (Pycharm/Clion) boundary.

**Comment by carlrobertoh** [comment]
Thank you for reporting!
The bug will be fixed in the next release.

**Comment by twidi** [comment]
Thanks a lot @carlrobertoh
