### ISSUE TITLE
Assistant message is blank when using customized system prompt.

### ISSUE THREAD

**Issue by itechbear** [carlrobertoh/CodeGPT#214]
### What happened?

With the System Prompt set in the Tools -> CodeGPT -> Configuration panel, CodeGPT would send empty assistant messages to server on chatting.

For example, the message of a request look like following:
```
[
Message(role=<Role.system: 'system'>, content='You are an assistant. You prefer answering in short words.'), 
Message(role=<Role.user: 'user'>, content='how are you ?'), 
Message(role=<Role.assistant: 'assistant'>, content=''), 
Message(role=<Role.user: 'user'>, content='Hi')
]
```

![image](https://github.com/carlrobertoh/CodeGPT/assets/3747635/0ee08bbc-58d6-41bc-8119-3c794e081206)

As you can see, the content of the third message is blank, while it should be `Fine.`  in my case. I did some debug and found that in the code, the value of the `prevMessage.getResponse()` is blank. I guess the bug must lie in somewhere in the conversation history management.

![image](https://github.com/carlrobertoh/CodeGPT/assets/3747635/a3b8e1f1-20f1-4f95-827b-5231fe39e331)

### Steps to reproduce

Go to the Settings -> Tools -> CodeGPT -> Configuration panel, set customized system prompt. For example: `You are an assistant. You prefer answering in short words.`.

Chat and capture the requests sent to the OpenAI server. 

### CodeGPT version

2.1.0

### Operating System

Windows

**Comment by carlrobertoh** [comment]
Should be fixed. Please reopen the ticket if it's still reproducible.
