### ISSUE TITLE
Settings with custom prompts

### ISSUE THREAD

**Issue by rangzen** [carlrobertoh/CodeGPT#22]
The thread starts in https://github.com/carlrobertoh/CodeGPT/issues/20

To bring prompts in another language, custom prompts, add personal prompts, fix prompts without waiting for a release, etc. it can be interesting to have this in the settings of the plugin with the form of a table with:
- a name, the same name will be used dynamically in the submenu of the right-click
- a prompt, with a limited form of formatting to include info like the part selected, the language detected, etc.

The Environment Variables of the Run configurations can be a good candidate for inspiration of the GUI.
Example:
![example](https://user-images.githubusercontent.com/132700/223470512-ed230e2e-673d-4158-8f4c-9499df3b9a5f.png)
You can see the name column with a short name to be reused in the GUI and prompts with some sort of formatting to dynamically be replaced during call `{{known part}}}`.

**Comment by rangzen** [comment]
For example, in the settings without the add, copy, delete, etc.
![image](https://user-images.githubusercontent.com/132700/223616394-0651a681-afd7-4e86-8185-80d120e19f50.png)

**Comment by rangzen** [comment]
https://github.com/rangzen/CodeGPT/tree/lme-custom-prompts-experiment

**Comment by carlrobertoh** [comment]
> For example, in the settings without the add, copy, delete, etc. ![image](https://user-images.githubusercontent.com/132700/223616394-0651a681-afd7-4e86-8185-80d120e19f50.png)

Perhaps it needs to be entirely new settings panel?

CodeGPT:
- Prompts

**Comment by rangzen** [comment]
https://github.com/dpayne/CodeGPT.nvim#overriding-command-configurations

**Comment by carlrobertoh** [comment]
Yeah, I think the value overriding shouldn't apply to prompts only.
Almost everything can be done via configuration table/settings, e.g. I think there's no point of creating some fancy user interfaces only to change some of the request params.

**Comment by rangzen** [comment]
https://minimaxir.com/2023/03/new-chatgpt-overlord/
Didn't know about the "system" part... Interesting

**Comment by carlrobertoh** [comment]
> https://minimaxir.com/2023/03/new-chatgpt-overlord/ Didn't know about the "system" part... Interesting

https://github.com/f/awesome-chatgpt-prompts/blob/main/prompts.csv

**Comment by carlrobertoh** [comment]
Thank you!
I will try to add more features step-by-step whenever I have time altho I'm worried about breaking stuff since the code lacks of tests.
