### ISSUE TITLE
Azure Openai GPT4 error: Unknown API response. Code: 200, Body:

### ISSUE THREAD

**Issue by heijligers** [carlrobertoh/CodeGPT#224]
### What happened?

trying to configure codegpt to work with azure openai deployment.
Getting:
Unknown API response. Code: 200, Body:

### Relevant log output or stack trace

```shell
Unknown API response. Code: 200, Body:
```

### Steps to reproduce
API-Version = 2023-07-01-preview

### CodeGPT version

2.1.5

### Operating System

macOS

**Comment by carlrobertoh** [comment]
Thank you for reporting! We will look into it.

**Comment by heijligers** [comment]
Thanks! I'll try it.

**Comment by emailtoakash** [comment]
Why 2023-07-01-preview does not work?

**Comment by Gquite** [comment]
The same problem is encountered

**Comment by Gquite** [comment]
How to solve it?

**Comment by Gquite** [comment]
![image](https://github.com/carlrobertoh/CodeGPT/assets/54300095/e1797b06-2dd6-44ca-9461-27e45a92c374)
Unknown API response. Code: 200, Body:

Relevant log output or stack trace
Unknown API response. Code: 200, Body:
Steps to reproduce
API-Version = 2023-07-01-preview

CodeGPT version
2.2.12

Operating System
windos 11

**Comment by webtechnic** [comment]
I am facing the same issue, please expedite the resolution.

**Comment by zhou-jian-qq** [comment]
I am facing the same issue.

**Comment by carlrobertoh** [comment]
Version 2.4.0 now provides the option to configure custom OpenAI-compatible services, including the ability to manually configure Azure service.

Please let me know if this helps.

<img width="723" alt="Screenshot 2024-02-26 at 16 02 38" src="https://github.com/carlrobertoh/CodeGPT/assets/15891408/77e4e338-1c16-4406-aaf8-e3364f9bee53">
