### ISSUE TITLE
Switch between models in the chat window

### ISSUE THREAD

**Issue by oscarlolero** [carlrobertoh/CodeGPT#227]
### Describe the need of your request

It would be nice to be able to quickly switch from one model to another by simple clicking on the models name.

![image](https://github.com/carlrobertoh/CodeGPT/assets/16091703/7acccfa6-c597-4e3d-8f12-54b2ccbc851f)

### Proposed solution

 Could be a dropdown or something similar.

**Comment by carlrobertoh** [comment]
I'll be updating the UI next week, which will include adding the option to change the models in the chat window.
<img width="622" alt="Screenshot 2023-11-24 at 13 34 17" src="https://github.com/carlrobertoh/CodeGPT/assets/15891408/a46ebbb4-33e8-4d53-9c27-1acc7929a0d1">

**Comment by AmicableTarsier** [comment]
Would this be something that could be added for the multiple Anthropic Claude 3 models?
