### ISSUE TITLE
CodeGPT stopped working in Goland

### ISSUE THREAD

**Issue by onselakin** [carlrobertoh/CodeGPT#231]
### What happened?

Here's a screenshot that shows the problem.

![image](https://github.com/carlrobertoh/CodeGPT/assets/10635384/66d440d9-b259-4709-8b43-17556a850faa)

I use the same OpenAI key with WebStorm and PyCharm and they work just fine without any problems.

### CodeGPT version

2.1.5

### Operating System

macOS

**Comment by carlrobertoh** [comment]
The message seems to be pretty clear. Please contact OpenAI for more information.
