### ISSUE TITLE
Stopped working in RustRover 2023.3

### ISSUE THREAD

**Issue by coostendorp** [carlrobertoh/CodeGPT#242]
### What happened?

After upgrading RustRover to 2023.3 (unavoidable since 2023.2 expired), CodeGPT is not working anymore.

Checking https://plugins.jetbrains.com/plugin/21056-codegpt then shows the message:
Not compatible with the version of your running IDE (RustRover 2023.3 EAP)

### Steps to reproduce

Upgrade RustRover to 2023.3 (unavoidable since 2023.2 expired), then run it.

### CodeGPT version

2.1.6

### Operating System

None

**Comment by jaseb** [comment]
@coostendorp 

Quick fix if you want to clone and build locally. As per docs, I just set the `until-build` to an empty string.

Edit `build.gradle.kts` and change the following line:
`untilBuild.set(properties("pluginUntilBuild"))`
Change to:
`untilBuild.set("")`

Build: 
`./gradlew clean build --no-build-cache`

Install plugin from disk:
Path - `build/distributions/CodeGPT-2.2.0.zip`

Docs: https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html

**Comment by carlrobertoh** [comment]
Thank you for reporting! This will be fixed in the next release, 2.2.1.
