### ISSUE TITLE
The icon is normal before you click on it, but it is abnormal after you click on it

### ISSUE THREAD

**Issue by MangerLe** [carlrobertoh/CodeGPT#25]
![image](https://user-images.githubusercontent.com/51878514/223612175-8fed540a-d258-4924-91a0-8efdf2d3a934.png)
![image](https://user-images.githubusercontent.com/51878514/223612215-157b9f6d-581d-4400-bb2a-f5d0c24d7c61.png)

**Comment by rangzen** [comment]
@carlrobertoh If I change the plugin.xml icon of toolWindow to a png of 13x13, I don't have the warning anymore, so probably the way to go.
