### ISSUE TITLE
other language models from openAI

### ISSUE THREAD

**Issue by daliagachc** [carlrobertoh/CodeGPT#250]
### Describe the need of your request

hi! i remember that in previous versions it was possible to select other language models? now we only have 3.4 and 4 

### Proposed solution

revert to the previous version

### Additional context

previous versions had other options

**Comment by bjonnh-work** [comment]
Another way would be to allow the users to specify a custom model besides the list. It would take less work than calling the models endpoint to get what the user has access to.

**Comment by carlrobertoh** [comment]
I will try to prioritize adding support for a custom model. However, as a quick fix, I have added the recently published models in v2.2.2.

**Comment by Q0** [comment]
> Another way would be to allow the users to specify a custom model besides the list.

It would be great! 

+1
