### ISSUE TITLE
Right click context menu is no longer clickable

### ISSUE THREAD

**Issue by Orad** [carlrobertoh/CodeGPT#251]
### What happened?

After upgrading I no longer able to click the CodeGPT plugin context menu.
It's a kotlin/android project. I have API keys set from before the latest plugin upgrade.

IntelliJ IDEA 2023.2.4 (Ultimate Edition)
Build #IU-232.10203.10, built on October 24, 2023
Runtime version: 17.0.8.1+7-b1000.32 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.1
Non-Bundled Plugins:
    ee.carlrobert.chatgpt (2.2.0)
    org.jetbrains.plugins.go-template (232.9921.89)
    org.jetbrains.plugins.go (232.10203.2)
    com.intellij.kubernetes (232.10203.2)
    org.intellij.plugins.hcl (232.8660.88)
    mobi.hsz.idea.gitignore (4.5.2)
    com.azoft.json2dart (1.0.3)
    com.jetbrains.packagesearch.intellij-plugin (232.9921.28)
    Dart (232.10072.19)
    com.hasintech.intellij.angularTemplates (1.1.3)
    com.github.masahirosuzuka.PhoneGapIntelliJPlugin (232.8660.88)
    Pythonid (232.10203.10)
    ru.meanmail.plugin.requirements (2022.4.1)
    com.intellij.plugins.html.instantEditing (232.8660.142)
    io.flutter (76.2.4)
    com.ruiyu.ruiyu (5.1.2)
    de.mariushoefler.flutter_enhancement_suite (1.7.0)
    name.kropp.intellij.makefile (232.8660.88)

Kotlin: 232-1.9.0-IJ10203.10

### CodeGPT version

2.2.0

### Operating System

macOS

**Comment by MattHag** [comment]
On PyCharm the context menu entry for CodeGPT is greyed out

**Comment by michabbb** [comment]
same in phpstorm

![image](https://github.com/carlrobertoh/CodeGPT/assets/3524595/690fbe8e-1ba8-4ce1-b254-78ca1d835631)

**Comment by zxfgds** [comment]
VERSION: phpstorm 2023.2.3
![image](https://github.com/carlrobertoh/CodeGPT/assets/25104815/ebb75806-0aa5-42c8-84c0-f34d885a1c68)

**Comment by jwcraig** [comment]
Same problem in Webstorm and Datagrip. I had to downgrade CodeGPT to 2.1.7

**Comment by carlrobertoh** [comment]
Thank you for reporting! This will be fixed in the next release, 2.2.1.

**Comment by carlrobertoh** [comment]
This will be fixed in the next release, 2.2.1. If it is not, please reopen the ticket.
