### ISSUE TITLE
Azure Service endpoint does not work with a proxy

### ISSUE THREAD

**Issue by emailtoakash** [carlrobertoh/CodeGPT#256]
### What happened?

When I try :
![image](https://github.com/carlrobertoh/CodeGPT/assets/6198894/a654358d-f83a-4b06-b9c3-e49539ab33f1)

I actually use a Azure Open AI service behind this proxy. I have my own endpoint and I use the key which is quite long. almost like a jwt token. I actually dont use the parameters there like resource, version etc. I just directly specify my endpoint

![image](https://github.com/carlrobertoh/CodeGPT/assets/6198894/98690274-cd4a-4d42-a990-c7bf0f3967f6)

### Relevant log output or stack trace

```shell
I dont know how to get the stacktrace. But I just get this error Unknown API response. Code: 200, Body:
```

### Steps to reproduce

I can help if needed

### CodeGPT version

2.2

### Operating System

Windows

**Comment by jsanko9** [comment]
https://github.com/carlrobertoh/CodeGPT/issues/224#issuecomment-1757156450

Did this help ?

**Comment by carlrobertoh** [comment]
From now on, all custom requests must now be configured in the 'Custom OpenAI Service' configuration panel (including Azure). Please create a new ticket if you encounter any problems with this.
