### ISSUE TITLE
proxy doesn't seem to be effective

### ISSUE THREAD

**Issue by wanniwa** [carlrobertoh/CodeGPT#26]
There is no problem with the api SECRET KEY and proxy configuration I use in other programs, but the answer in this plug-in is always loading

**Comment by wanniwa** [comment]
<img width="448" alt="image" src="https://user-images.githubusercontent.com/26156945/223632874-556a5d2f-aabd-4cb6-a599-926320413f81.png">

**Comment by qlaall** [comment]
你可以贴一下你插件的设置，在Settings-Tools-CodeGPT，把key打一下码，主要看HTTP/SOCKS Proxy这部分，同时看一下你代理工具的socks代理的端口，看看是否对应。
当无法连接代理的时候就会提示“Something went wrong. Please try again later.” 比如Host/Port这边设置和代理工具不对应的时候。

**Comment by wanniwa** [comment]
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/26156945/223635123-e45f784e-ab01-4e1e-a0cd-5d6e19dccf63.png">

**Comment by wanniwa** [comment]
same setting in this project is ok 
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/26156945/223635513-94efc32c-b0ce-40a1-b2c8-ae816f243fe7.png">

**Comment by qlaall** [comment]
你这里可能有这个问题，就是代理区分HTTP和socks协议，你第二张图这样设置实际上没有显示7890端口使用什么协议，你可以改成http协议的代理看看，就是CodeGPT插件的Proxy设置不要使用SOCKS(socks5)，而使用HTTP

**Comment by wanniwa** [comment]
<img width="767" alt="image" src="https://user-images.githubusercontent.com/26156945/223638430-bf3e8463-9c9a-4841-9f2b-23f8e22f6ccf.png">
这个端口

> 你这里可能有这个问题，就是代理区分HTTP和socks协议，你第二张图这样设置实际上没有显示7890端口使用什么协议，你可以改成http协议的代理看看，就是CodeGPT插件的Proxy设置不要使用SOCKS(socks5)，而使用HTTP

这个端口连个协议都支持的

**Comment by qlaall** [comment]
我看出问题了 你这里写成172.0.0.1了

**Comment by wanniwa** [comment]
> 我看出问题了 你这里写成172.0.0.1了

127?!!!!!!  thank you!

**Comment by carlrobertoh** [comment]
Thank you @qlaall!
