### ISSUE TITLE
Use CodeLLama remote server instead of running model locally

### ISSUE THREAD

**Issue by gejgalis** [carlrobertoh/CodeGPT#260]
### Describe the need of your request

There are projects with dedicated/hosted server with already running CodeLLama remotely.

### Proposed solution

It would be great to use `hostname:port` or URL to remote CodeLLama instance instead of running it locally (too many resources needed on laptop)

### Additional context

The plugin works great so far!

**Comment by carlrobertoh** [comment]
Thank you!
I will improve the llama configuration in the near future, including overriding the base host, to enable support for connecting to remote servers.

**Comment by hoh** [comment]
Related to https://github.com/carlrobertoh/CodeGPT/issues/269

**Comment by sbaier1** [comment]
as a temporary workaround, you can also run the model inference on this webui https://github.com/oobabooga/text-generation-webui , then enable the API and set the openAI API to the host running the API. this works for me to use a remote hosted codellama model.

**Comment by snacsnoc** [comment]
@sbaier1 Thanks for the workaround, this works!
Run `text-generation-webui`, eg:
```
./start_macos.sh --auto-devices --numa --api --api-key 0000 
```
Go into the webui, http://127.0.0.1:7860, and load your model. Optionally, load it with the `--model` option.
In CodeGPT (PyCharm), use OpenAI, pick any GPT option.
Enter the API key you made with `--api-key`
For the base host, use: `http://127.0.0.1:5000`
Path: `/v1/chat/completions`
