### ISSUE TITLE
Replace Selection should apply Reformat and cleanup... function after pasting code

### ISSUE THREAD

**Issue by AlexanderLuck** [carlrobertoh/CodeGPT#262]
### Describe the need of your request

Hi, great tool.
One QoL issue I have is that when using the Replace Selection function of the code window the inserted code is always out of format. It would be great if (maybe optionally) it would trigger a reformat and cleanup run after inserting it into the code.

### Proposed solution

Add option to auto format generated code for all functions that paste generated code.

**Comment by carlrobertoh** [comment]
Thank you for the request! Auto-formatting support will be available in v2.2.6 (sometime early next week).
