### ISSUE TITLE
Add support OpenAI GPT-4 Turbo model

### ISSUE THREAD

**Issue by fantom0005** [carlrobertoh/CodeGPT#266]
### Describe the need of your request

OpenAI have released a new version of GPT 4. It is better, faster and cheaper. 

Please add support for it

**Comment by carlrobertoh** [comment]
GPT-4 Turbo is available in version 2.2.2.
https://github.com/carlrobertoh/CodeGPT/issues/261

**Comment by fantom0005** [comment]
Sorry, I thought I had already updated. thank you very much! 
@carlrobertoh
