### ISSUE TITLE
"Request timed out" for local Llama server

### ISSUE THREAD

**Issue by markuswolff** [carlrobertoh/CodeGPT#268]
### What happened?

I am using CodeGPT 2.2.2 with PHPStorm 2023.03 EAP Build #PS-233.11555.19, running as a Snap package on Ubuntu 22.04.

The plugin is configured to use a local Llama model. I downloaded the CodeLlama 7B model via the settings screen and started the server with default settings (port 44925).

The server is running correctly, and is reachable from a browser via HTTP. I can send prompts and receive answers through the web interface.

However, when I try to use the CodeGPT functions from within PHPStorm, e.g. select a method, right-click and select "Write Tests" or "Find Bugs", then the only response I'm getting is:

> "Request timed out. This may be due to the server being overloaded."

Expectation: I would receive some output similar to what I get when I manually prompt the model via HTTP.

### Steps to reproduce

* Install PHPStorm 2023.03 EAP
* Install CodeGPT plugin 2.2.2
* Open settings screen and select Tools > CodeGPT
* Select local Llama model
* Download Codellama 7B via plugin settings screen
* Start local Llama.cpp server via plugin settings screen
* Open a PHP class file
* Select a method
* Right-click and from the CodeGPT context menu, select the "Write Tests" option (or any other)
* Marvel at the timeout message

### CodeGPT version

2.2.2

### Operating System

Linux

**Comment by eduard-sukharev** [comment]
Same here. In `htop` I can see that server actually got the query and working hard on makeing a response, but no one is waiting for that - the `Request timed out` error is there after about 5 seconds. No way to tweak the timeout for local LLama server (tested with multiple GGUF models).

**Comment by xiangtianyu** [comment]
I have the same problem, is there any progress on this now?

**Comment by carlrobertoh** [comment]
Hi, please try upgrading the plugin to v2.2.4.
The timeouts have been increased to 30 seconds, and if this is still insufficient, then it can be configured via Settings | CodeGPT | Configuration.

**Comment by eduard-sukharev** [comment]
Works for me in 2.2.4. I have noticed that after I started receiving the response from server, but not finished yet I might get the timeout message, but that doesn't interfere with anything and is not a problem anymore.
