### ISSUE TITLE
Context menu items do not work since 2.2.3

### ISSUE THREAD

**Issue by HerrC** [carlrobertoh/CodeGPT#272]
### What happened?

If i highlight a code and select in the context menu of IntelliJ CodeGpt -> Optimize/Custom prompt, or other, it opens a new Chat window but does not trigger a request. The chat is still empty.

If I enter text into the chat window it works as expected.

### Steps to reproduce

Open a Kotlin file (.kt)
Select the code.
Right mouse and select an entry from the context-menu. (CodeGpt...)
No result in the chat window.

### CodeGPT version

2.2.3

### Operating System

Windows

**Comment by carlrobertoh** [comment]
Thank you for reporting! I will investigate the issue as soon as I find some time.

**Comment by delmicio** [comment]
Same issue here. A workaround is disabling the "Open new tab on each action" setting

CodeGPT version
2.2.4

Operating System
13.5.2 (22G91)

**Comment by carlrobertoh** [comment]
This issue will be fixed in v2.2.5.

**Comment by michabbb** [comment]
this problem came back 😕 https://github.com/carlrobertoh/CodeGPT/issues/567
