### ISSUE TITLE
LICENSE file on github doesn't match the listed license on the IntelliJ marketplace

### ISSUE THREAD

**Issue by estradanic** [carlrobertoh/CodeGPT#275]
### What happened?

Intellij marketplace page lists Apache 2.0 as the license https://plugins.jetbrains.com/plugin/21056-codegpt (scroll down and click License, which links to Apache license).

The LICENSE file here is an MIT license. These should not be different, as it complicates getting access to use CodeGPT at many companies, especially security-focused companies that require all external software to be approved.

### CodeGPT version

2.2.3

### Operating System

None

**Comment by carlrobertoh** [comment]
Thank you for pointing it out! The license has now been changed to Apache 2.0.
