### ISSUE TITLE
Long responses are being cut off

### ISSUE THREAD

**Issue by GiGurra** [carlrobertoh/CodeGPT#277]
### What happened?

GPT4-turbo can produce long results and handle long inputs. However, it seems that the codegpt plugin currently cuts answers of if the total token count gets to around 2300.

The exact same questions and answers work fine if I use the gpt API directly, so I'm not sure why it is being cut off in the intellij codeGPT plugin

### Steps to reproduce

Just send in an input of maybe 1000-1500 tokens and ask it to rewrite it in another language/form, so it will produce lots of output.

Example: I have an old react js + class codebase I am converting to functional components with typescript. This works great with gpt4-turbo, but codeGpt is cutting off half of my conversions :D.

### CodeGPT version

232.9826

### Operating System

macOS

**Comment by carlrobertoh** [comment]
Hi, try increasing the output completion tokens value in the settings via CodeGPT | Configuration | Max completion tokens.

**Comment by GiGurra** [comment]
> Hi, try increasing the output completion tokens value in the settings via CodeGPT | Configuration | Max completion tokens.

Unfortunately I think we need an updated plugin. Even if I increase the setting I get this:

![image](https://github.com/carlrobertoh/CodeGPT/assets/1761299/de7d9f08-4077-4946-9b92-f4b6806922df)

**Comment by GiGurra** [comment]
Oh it seems the output limit is 4096. But the input/context window limit is 128k.
