### ISSUE TITLE
Button to "Continue" generation of response

### ISSUE THREAD

**Issue by eduard-sukharev** [carlrobertoh/CodeGPT#288]
### Describe the need of your request

Some responses might reach the limit of the output length and stop mid-file. There's no way to nudge the llama.cpp server to go on and generate further to complete the code in a file.

![image](https://github.com/carlrobertoh/CodeGPT/assets/3235378/5756dcb8-1922-41ad-ae7c-d96df24adffb)

### Proposed solution

The [text-generation-webui](https://github.com/oobabooga/text-generation-webui) has a chat query option to finish the response from the point where it left.

We need similar button in the UI.

**Comment by ViktorGozhiy** [comment]
In my case just the `Continue` message works

**Comment by carlrobertoh** [comment]
`n_predict` must be set to `-1`, which controls the length of the generated text

**Comment by eduard-sukharev** [comment]
> `n_predict` must be set to `-1`, which controls the length of the generated text

How one sets that parameter? When I start the server it is now started as following (from `ps aux` output):
```
./server -m /home/user/mistral-7b-code-16k-qlora.Q6_K.gguf -c 2048 --port 37717
```

Which parameter to toggle in UI? is it available now?

**Comment by carlrobertoh** [comment]
This is a request parameter that is currently not configurable.
I will add the support in v2.2.6 (sometime early next week).
