### ISSUE TITLE
Is there a GPU support for local LLM's?

### ISSUE THREAD

**Issue by koolvn** [carlrobertoh/CodeGPT#297]
Hi and **thank you** for your work!
I wonder if it is possible to use GPU for local LLMs "from the box" or should I build and run server of `llama.cpp` to make it happen?
CPU inference is slow even when using all of my 32 threads...

**Comment by koolvn** [comment]
Thank you for a quick response! I'll try building llama.cpp from source. 

Closing the issue.

**Comment by 0x131315** [comment]
i think need write this instruction in README
