### ISSUE TITLE
microservice endpoint generation through BYOK model

### ISSUE THREAD

**Issue by jdhamelia** [carlrobertoh/CodeGPT#305]
### Describe the need of your request

Hello There, I have used this for sometime and really appreciate all the people involved in making this.

I was wondering if its feasible to add a feature which based on just chat message generates endpoint code for you which can be any PUT, POST, GET etc. ?

**Comment by jdhamelia** [comment]
Another question, is there any plan to add support eclipse IDE for this plugin?

**Comment by carlrobertoh** [comment]
Thank you!

What exactly do you mean by 'generating endpoint code'? Would overriding the system prompt help?

> Another question, is there any plan to add support eclipse IDE for this plugin?

Unfortunately, support for Eclipse IDE is not on the roadmap at the moment.
