### ISSUE TITLE
Configuration for localhost or on prem LLaMA server

### ISSUE THREAD

**Issue by Thibault-Pelletier** [carlrobertoh/CodeGPT#307]
### Describe the need of your request

Hi,

First of, great work with this plugin!

I was wondering if it would be possible to enable an On Prem LLaMA C/C++ configuration in the UI.

The ` LLaMA C/C++` option seems to only be available in the options for Linux MacOS, but there are some configurations where Windows users could also connect to a WSL server instance on their localhost or just connect to an LAN instance.

Launching the prompt would work but would only work if the LLaMA server is configured on Localhost on the default 64531 port at the moment.
It would probably work to only disable launching the server for the  LLaMA C/C++ on Windows and keep the IP / Port configuration side.

Thanks in advance,
Best,
Thibault

**Comment by carlrobertoh** [comment]
Hi,

I agree, enabling users to configure the host and port would be sufficient before we can actually support running the server on OSs other than UNIX. 

I will add the support as soon as I have some time.

**Comment by Bmooij** [comment]
Hi,

Maybe this will help, ollama just went in preview on windows. And it has an API that runs on `http://localhost:11434`

https://ollama.com/blog/windows-preview

**Comment by Thibault-Pelletier** [comment]
@Bmooij thanks for the info! I will have a look :)
