### ISSUE TITLE
Feature Request: Implement Shortcut Keys for Directory Level Navigation

### ISSUE THREAD

**Issue by lyrl** [carlrobertoh/CodeGPT#314]
### Describe the need of your request

Set shortcut keys for directory levels so that I can quickly navigate to the prompt I need without having to set a shortcut key for each prompt.

Official support：
![image](https://github.com/carlrobertoh/CodeGPT/assets/1203738/f1f05ce7-1344-43c9-847f-e1cb745f404e)

CodeGpt:
![image](https://github.com/carlrobertoh/CodeGPT/assets/1203738/004d0e03-9074-4e9a-aaf8-11b256502983)

Expect:
![image](https://github.com/carlrobertoh/CodeGPT/assets/1203738/05c22f12-1993-4812-8876-801c992ff2b3)

**Comment by PhilKes** [comment]
I'm not sure if this changed up until now, but is this still relevant?
In IntelliJ's `Keymap` Setting you can define Shortcuts for all CodeGPT Actions as well as custom Prompts:
![image](https://github.com/carlrobertoh/CodeGPT/assets/39240633/5f272ace-89b0-426f-bb20-4a4b38081db3)

**Comment by lyrl** [comment]
I want to add shortcut keys at this level, so that all prompts can be displayed without setting a shortcut key for each prompt.
![54529](https://github.com/carlrobertoh/CodeGPT/assets/1203738/9a00218c-c748-43cc-95b5-2a96b8e9c454)

**Comment by lyrl** [comment]
![CleanShot 2024-05-08 at 18 02 51](https://github.com/carlrobertoh/CodeGPT/assets/1203738/7f4ee44e-56e4-4e76-9140-d43b43d80066)
Hoping to achieve this, right now I'm calling code-gpt with actions
