### ISSUE TITLE
Please provide a mechanism to delete downloaded models

### ISSUE THREAD

**Issue by abhiyansm** [carlrobertoh/CodeGPT#328]
### Describe the need of your request

I downloaded a model to use with codegpt (https://i.imgur.com/so3UF96.png). It didn't work out - my system wasn't quite upto the mark and kept timing out, running out of memory etc. Now I want to delete the locally downloaded model as its quite a significant usage, but cannot find a way to do so. 

### Proposed solution

There should be an easy way to remove locally downloaded model. Or at least should be documented how users may delete those in a safe way.

**Comment by abhiyansm** [comment]
I mean it is possible to delete it manually by going into the config folders (on debian) and removing the model file, but it would be a good experience to be able to return to a clean slate from the plugin itself.

**Comment by MuhammadMuzammilQadri** [comment]
How to delete models on mac?

**Comment by MuhammadMuzammilQadri** [comment]
Never mind, found the location for the downloaded models:
`~/.codegpt/models`

**Comment by carlrobertoh** [comment]
Duplicate of #330
