### ISSUE TITLE
[Question] Data Privacy & Code Security Concerns

### ISSUE THREAD

**Issue by tushar-srivastav** [carlrobertoh/CodeGPT#332]
I am experimenting with this plugin and it is amazing. My concern is that I want to use it in an enterprise and even though it's a BYOK (Bring your own [API] key) model, I am concerned with respect to its usage in an enterprise environment.

Can you please provide the list of trackers, and data-privacy policy if any to be sure that it is safe to use in such scenarios.

**Comment by carlrobertoh** [comment]
Great question!

CodeGPT does not use any 3rd party services as proxies for LLM providers; therefore, we don't send or save any user-specific data.
However, with users' consent, we do collect anonymous usage data on how the extension is used. We primarily collect data to understand how users interact with the extension, including the most-used features and preferred providers. Importantly, we **DO NOT** record or store any API keys or messages exchanged with the services.

Links to [privacy policy](https://codegpt.carlrobert.ee/privacy) and [telemetry implementation](https://github.com/carlrobertoh/CodeGPT/tree/master/codegpt-telemetry).
