### ISSUE TITLE
Add support for Ollama

### ISSUE THREAD

**Issue by Crown0815** [carlrobertoh/CodeGPT#343]
### Describe the need of your request

Run a local or remote [ollama](https://ollama.ai/library) server as backend.

### Proposed solution

Connect to the Ollama port similar to [Ollama webui](https://github.com/ollama-webui/ollama-webui)

**Comment by sclark-dev** [comment]
I second this. Ollama already has a well documented API. The ability to use a local AI, and being able to choose which model would make this a must-have plugin.

**Comment by gschrader** [comment]
The latest version of Ollama now has OpenAI compatibility, all is needed is to be able to specify the model name now.

**Comment by gschrader** [comment]
Actually ignore my last comment the docs suggest you can copy a model with matching name:
`
ollama cp llama2 gpt-3.5-turbo
`
Seems to be working for me!

**Comment by monksy** [comment]
Still it would be nice to have the plugin pull a listing of available models instead of the hard coded OpenAPI ones when you have this configured.

**Comment by OleksandrWebLab** [comment]
It helped me:

https://github.com/ollama/ollama/blob/main/docs/openai.md

https://github.com/ollama/ollama/issues/2474

**Comment by kalifg** [comment]
I am trying to get this to work, even with copying the model and ollama v0.1.25 — all I get from CodeGPT is "404 page not found".

**Comment by PabloMzSAP** [comment]
I got this error:
404 page not found

java.lang.RuntimeException
	at ee.carlrobert.llm.completion.CompletionEventSourceListener.onFailure(CompletionEventSourceListener.java:114)
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:52)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by carlrobertoh** [comment]
Version 2.4.0 is now publicly available, providing the option to configure custom OpenAI-compatible services, including the preset template for Ollama.

Please let me know if it helps.
