### ISSUE TITLE
Local run of the plugin fails 

### ISSUE THREAD

**Issue by raivisdejus** [carlrobertoh/CodeGPT#347]
### What happened?

Running the plugin locally fails with `FAILURE: Build failed with an exception.`

### Relevant log output or stack trace

```shell
https://gradle.com/s/vjftbm7a5abqg
```

### Steps to reproduce

git clone https://github.com/carlrobertoh/CodeGPT.git
cd CodeGPT
git submodule update
./gradlew runIde

### CodeGPT version

master @ 390d8cd

### Operating System

Linux

**Comment by carlrobertoh** [comment]
Hi, please try building the plugin using Java 11. Based on the stack trace, it seems that you are currently using Java 8.

**Comment by raivisdejus** [comment]
Indeed, updating to Java 11 fixed the issue.
Thanks!
