### ISSUE TITLE
Support for together.ai OpenAPI endpoints

### ISSUE THREAD

**Issue by keriati** [carlrobertoh/CodeGPT#359]
### Describe the need of your request

Thank you for working on this awesome plugin. 
together.ai provides an openai compatible endpoint that could work, except they have a wide range of models with different names.

### Proposed solution

allow to use custom model name
or
load all available models from the api instead of hardcoding them.
(openai api provides a list of available models)

### Additional context

awesome plugin, love it

**Comment by carlrobertoh** [comment]
Hey,

Version 2.4.0 is now publicly available, providing the option to configure custom OpenAI-compatible services.
Please let me know if it helps.
