### ISSUE TITLE
How to make CodeGPT for pycharm fonts larger or zoom in?

### ISSUE THREAD

**Issue by luckyhug** [carlrobertoh/CodeGPT#36]
It's a great tool. I'm wondering if there is a way to make CodeGPT larger and easy to read in pycharm?

**Comment by carlrobertoh** [comment]
Hi, at the moment the ToolWindow's text isn't relative to IDE's font sizes, I will try to fix it in the upcoming days.

**Comment by carlrobertoh** [comment]
Hi, the relative fonts are available in version 1.6.1.
<img width="1261" alt="Screen Shot 2023-03-17 at 15 37 57" src="https://user-images.githubusercontent.com/15891408/225951669-adf9c385-9d00-48cd-92e8-0a5f4a4338c7.png">
