### ISSUE TITLE
How to enable inline autocompletion?

### ISSUE THREAD

**Issue by dginovker** [carlrobertoh/CodeGPT#365]
### Describe the need of your request

Hi - I see in the 2.3.0 release notes, autocompletion is disabled by default: https://github.com/carlrobertoh/CodeGPT/commit/4ccba567d98bacedf485428ba97ee196f0f12ab4

Is there a setting to enable this?

### Additional context

I know this is a new/alpha feature, so if there's no setting that's fine :smile:. If there is a way to enable it though as a regular user and I just can't find it in the UI, please let me know!

**Comment by dginovker** [comment]
![image](https://github.com/carlrobertoh/CodeGPT/assets/32943174/fa0b530a-c773-47c9-8f54-34e9d6b87927)

Looks like you can click the CodeGPT logo in the bottom right to enable/disable it

**Comment by dginovker** [comment]
Hmm doesn't seem to be doing anything on either with either OpenAI or LLaMA as a Service. Nothing in the logs either. Maybe I'll wait for next release :yum:

**Comment by carlrobertoh** [comment]
This is still WIP and barely usable at the moment 😄

**Comment by dginovker** [comment]
Barely usable? My coworker's brain melted when he saw it and already is in love :joy:

**Comment by carlrobertoh** [comment]
I'm glad to hear that, it keeps me motivated to improve the functionality. I personally find it not usable at the moment. 😄

**Comment by jlatiav** [comment]
I just noticed that you disabled the code completion feature for Azure and You services (5a88a7d9f3556302a222706a6f43343f14a89aaf).
Will these services support code completion in the future?

Thank you for your work!

**Comment by carlrobertoh** [comment]
I don't have access to Azure, so I couldn't test this. You service is simply waiting for its time to be deleted, right now it's available for its free usage.

**Comment by marek-mazur** [comment]
@carlrobertoh OMG why this option for competition is so hidden in JetBrains products? I have been thinking for a long time that is available for Visual Studio Code only... Can it be added to Settings?

**Comment by dginovker** [comment]
> @carlrobertoh OMG why this option for competition is so hidden in JetBrains products? I have been thinking for a long time that is available for Visual Studio Code only... Can it be added to Settings?

It's because it's not ready yet

**Comment by marek-mazur** [comment]
> > @carlrobertoh OMG why this option for competition is so hidden in JetBrains products? I have been thinking for a long time that is available for Visual Studio Code only... Can it be added to Settings?
> 
> It's because it's not ready yet

Thx. I see. Still, it could be marked as a Beta/Unstable feature disabled by default

**Comment by carlrobertoh** [comment]
@EPGDigital-MW The feature is available only for OpenAI and llama.cpp services at the moment.

**Comment by adrienbrault** [comment]
Hey, I would also like to have inline code completions with "Custom OpenAI Service" (and Ollama).

It took me a while to understand why it wasn't working, maybe consider mentioning the lack of inline completion on https://plugins.jetbrains.com/plugin/21056-codegpt

**Comment by carlrobertoh** [comment]
Closing this ticket.

@adrienbrault Inline code completions with 'Custom OpenAI Service' are available in the latest version. However, Ollama is not supported yet. I'll try to add it soon.
