### ISSUE TITLE
Code Inline Completion change to v1/chat/completions

### ISSUE THREAD

**Issue by Q0** [carlrobertoh/CodeGPT#369]
### What happened?

I am using a dedicated service provider for OpenAI models and use `Base host`. In a new function (Code Inline Completion), the `v1/completions` method is called. This method is not available from my service provider. This method is Legacy in the OpenAI documentation, and also it is most often not available on new models. 

Is it possible to change the method to `v1/chat/completions`?

### CodeGPT version

2.3.0

**Comment by mgls23** [comment]
Thought I might chime in here with LM studio (and the result it expects)

![Screenshot 2024-02-17 at 20 48 28](https://github.com/carlrobertoh/CodeGPT/assets/5109678/12072142-6f7b-4ed2-9956-47b59cb13e51)

**Comment by mgls23** [comment]
@Q0 in the meantime, it looks like you can use OpenAI API query to get around this problem. You can find this in

Pycharm Settings > Tools > CodeGPT
![Screenshot 2024-02-17 at 21 12 33](https://github.com/carlrobertoh/CodeGPT/assets/5109678/30500566-5f05-4f7e-a2f5-bf0fbc2ae9be)

**Comment by Q0** [comment]
The main functionality of the plugin works correctly due to the use of Path `/v1/chat/competions`. However, the Code Inline Completion function uses a different method

https://github.com/carlrobertoh/CodeGPT/blob/4ccba567d98bacedf485428ba97ee196f0f12ab4/src/main/java/ee/carlrobert/codegpt/completions/CompletionRequestService.java#L81

which in turn calls the method

https://github.com/carlrobertoh/llm-client/blob/6df58820199596dc0531c67af47fa01289e04c53/src/main/java/ee/carlrobert/llm/client/openai/OpenAIClient.java#L121

and it uses `/v1/completions`.

As I said earlier, this method is not available from many service providers for OpenAI models.

Another reason is that the `Path` setting does not affect the Code Inline Completion function

**Comment by carlrobertoh** [comment]
> This method is Legacy in the OpenAI documentation, and also it is most often not available on new models.

@Q0 The only way to gain access to their `gpt-3.5-turbo-instruct` model is through the `/v1/completions` API endpoint. Their docs are misleading; although it states that the entire service is deprecated, their recent [deprecation docs](https://platform.openai.com/docs/deprecations/instructgpt-models) recommend it as a replacement for older models, and [no words](https://platform.openai.com/docs/models/gpt-3-5-turbo) of deprecation.

I'm happy to change it to `/v1/chat/completions` if someone could tell me how.
