### ISSUE TITLE
About Reverse proxy url

### ISSUE THREAD

**Issue by fatebugs** [carlrobertoh/CodeGPT#37]
i have my own Reverse proxy,I want to be able to Reverse proxy url to modify,So can I trouble you to support the opening of custom input?thanks
![image](https://user-images.githubusercontent.com/65278566/224541410-8c266f66-b2be-409f-9252-c278387ec9a7.png)

**Comment by carlrobertoh** [comment]
Hi, I'll try to add the support in the upcoming days.
FYI: The reverse proxy was replaced with the working one in version 1.4.3

**Comment by carlrobertoh** [comment]
@fatebugs I'm considering removing the support for unofficial reverse proxy, is there any reason why you'd want to use your own reverse proxy?

Thank you

**Comment by fatebugs** [comment]
Because my region is in China, I can only access Chat gpt through an unofficial reverse proxy for my locked zone,Therefore, reverse proxies are very important to me, especially custom reverse proxiesSo please be sure to leave this function behind and add customizable options



---Original---
From: ***@***.***&gt;
Date: Sun, Mar 19, 2023 01:58 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [carlrobertoh/CodeGPT] About Reverse proxy url (Issue #37)




 
@fatebugs I'm considering removing the support for unofficial reverse proxy, is there any reason why you'd want to use your own reverse proxy?
 
Thank you

**Comment by carlrobertoh** [comment]
Using the official API via proxy isn't an option?
The thing with custom reverse proxies is that there's no easy way for me to track nor debug the issues because each person might have different setup.

**Comment by fatebugs** [comment]
Indeed, when you say this, I realized that,it seems that I can access the API through proxy,Thank you for your reply，Sorry for the inconvenience.My English level may not be so good, so there are some words that don't convey my meaning



---Original---
From: ***@***.***&gt;
Date: Sun, Mar 19, 2023 17:54 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [carlrobertoh/CodeGPT] About Reverse proxy url (Issue #37)




 
Using the official API via proxy isn't an option?
 The thing with custom reverse proxies is that there's no easy way for me to track nor debug the issues because each person might have different setup.

**Comment by carlrobertoh** [comment]
Happy to help!
If everything seems to be working correctly then please close the ticket, thank you!
