### ISSUE TITLE
CodeGPT incorrectly displays API key not provided for Azure Service

### ISSUE THREAD

**Issue by jlatiav** [carlrobertoh/CodeGPT#375]
### What happened?

With the 2.3.0 update, CodeGPT responds with `API key not provided. Open Settings to set one.` to my chat messages. Downgrading to 2.2.12 fixes the problem.

The settings still display a dotted-out API key for Azure.

I'm using PyCharm 2023.3.3 on Win10.

Please let me know if I can provide further information to debug the issue.

### CodeGPT version

2.3.0

### Operating System

Windows

**Comment by carlrobertoh** [comment]
Thank you for reporting! This will be fixed in v2.3.1.
