### ISSUE TITLE
Wrong Chat Completion algorithm is used

### ISSUE THREAD

**Issue by PascalSenn** [carlrobertoh/CodeGPT#38]
Hi there and thanks for creating `CodeGPT`!

It appears that no matter what I select, the extension always uses  `gpt-3.5-turbo-0301` and not `gpt-3.5-turbo`. Is this by design or am i missing something? 

![image](https://user-images.githubusercontent.com/14233220/224572457-59159421-55f7-4896-9a07-168fa3d161fb.png)

![image](https://user-images.githubusercontent.com/14233220/224572784-d452716a-2049-485b-aee3-db4719ac8e6f.png)

**Comment by carlrobertoh** [comment]
Hi @PascalSenn

The model used in the request is taken from the settings and right now I can't see an issue related to that. Perhaps the data in OpenAI comes with a delay?

FYI: There's a known bug - when you switch the model while having an open conversation then it doesn't create a new session with the new model(workaround for that is to click `Ask ChatGPT` from the menu again). You can find the model that was used in the `Conversation History` tab.

Also, are you using the recent version?

Best regards

**Comment by PascalSenn** [comment]
@carlrobertoh 

That's the strange thing. The model from Conversation History doesn't correspond with the model from OpenAI.

OpenAI:
![image](https://user-images.githubusercontent.com/14233220/224576096-ddaf180e-9ef5-42d6-bf02-65e5cbf5f01f.png)

Conversation History:
![image](https://user-images.githubusercontent.com/14233220/224576101-2958ac08-6b17-46be-a270-0c62f579a645.png)

>There's a known bug - when you switch the model while having an open conversation then it doesn't create a new session with the new model(workaround for that is to click Ask ChatGPT from the menu again)

I doubt that this is the case. I have even restarted the IDE several times in between. 
I am using the EAP 8 and 1.4.2

**Comment by carlrobertoh** [comment]
Apparently this is an OpenAI side issue.

> In the request you specify with “gpt-3.5-turbo” that you want to use the latest version of the model. This is currently gpt-3.5-turbo-0301, so this is the model you see in the response. Should there be 0302 in the future, then this would be the model used in the answer.

https://community.openai.com/t/attempting-to-use-gpt-3-5-turbo-getting-gpt-3-5-turbo-0301-instead/94411/4


Sorry for the confusion.

**Comment by carlrobertoh** [comment]
No problem, happy to help!
