### ISSUE TITLE
Requires JavaScript to be enabled

### ISSUE THREAD

**Issue by Soufdsfe65w** [carlrobertoh/CodeGPT#389]
### What happened?

**OpenAI** **customizes** the key and server address and keeps reporting this error: Unknown API response. Code: 200, Body: You need to enable JavaScript to run this app.

### CodeGPT version

2.4.0

### Operating System

Windows

**Comment by carlrobertoh** [comment]
What do you mean by "OpenAI customizes the key and server address"? Are you using the Custom OpenAI service or the actual one with proxy?

**Comment by Soufdsfe65w** [comment]
> “OpenAI 自定义密钥和服务器地址”是什么意思？您使用的是自定义 OpenAI 服务还是带代理的实际服务？

There is a custom option for OpenAI. The interface and secret key can be customized.

**Comment by carlrobertoh** [comment]
The error "You need to enable JavaScript to run this app" is caused by the server, indicating that the configuration you are using is incorrect. Can you get the correct response by invoking a simple `cURL` request, for example?

**Comment by reneleonhardt** [comment]
@Soufdsfe65w Can you still reproduce this problem with CodeGPT 2.5.1 and for example https://docs.codegpt.co/docs/tutorial-ai-providers/ollama?
