### ISSUE TITLE
Custom OpenAl Service will auto change to  OpenAl Service

### ISSUE THREAD

**Issue by linpan** [carlrobertoh/CodeGPT#391]
### What happened?

I set Custom OpenAl Service ,  then sometime will error, 
![CleanShot 2024-03-02 at 15 17 09](https://github.com/carlrobertoh/CodeGPT/assets/6077601/594ad9fc-cf8a-4fd1-b3f7-92646adfe1ef),
open setting: OpenAl Service

my custom  "Custom OpenAl Service " change to  OpenAl Service

### CodeGPT version

2.4.0

### Operating System

macOS

**Comment by reneleonhardt** [comment]
@linpan Can you still reproduce the problem with CodeGPT 2.5.1?

If yes, can you post the stacktrace?
* `Help / Show log in Finder` (on Mac)
* Open `idea.log`
* Search from the end of the file: `at ee.carlrobert.codegpt`
* If you find such a `SEVERE - ` block, post the whole stacktrace here until the last `at ` line (before the next `2024-04-` line)

There could also be a little red icon (bottom right) `IDE Internal Error Occured`:
* Press the icon to open the dialog `IDE Internal Errors`
* Navigate to the first entry by clicking the left arrow (upper left) until you go back to 1.

**Comment by carlrobertoh** [comment]
This issue should be fixed in the latest version. Please reopen the ticket if it's still reproducible.
