### ISSUE TITLE
OpenAi token cant get saved

### ISSUE THREAD

**Issue by HASKADOG** [carlrobertoh/CodeGPT#395]
### What happened?

I provided my openai token in the plugin settings, it works until pycharm reboot. 

### CodeGPT version

latest

### Operating System

Linux

**Comment by carlrobertoh** [comment]
The secret is stored in either Keychain or KeePass, depending on your OS. Make sure that you haven't selected the third option.

<img width="693" alt="Screenshot 2024-03-04 at 12 02 26" src="https://github.com/carlrobertoh/CodeGPT/assets/15891408/2828ce52-edef-41f8-b991-0c3de44ff126">

**Comment by HASKADOG** [comment]
@carlrobertoh I'm stupid... You are right! Thank you!
