### ISSUE TITLE
Support for Claude 3 api

### ISSUE THREAD

**Issue by tjaadvd** [carlrobertoh/CodeGPT#396]
### Describe the need of your request

Hi,
Claude 3 has just been released and according to [their announcement ](https://www.anthropic.com/news/claude-3-family)Claude 3 Opus scores better than GPT-4 on code tasks (HumanEval).

It would be great if this plugin supports the Anthropic api too so that we can take advantage of that!

Greetings,
Thomas

**Comment by GiGurra** [comment]
I'd also love to see this!

**Comment by carlrobertoh** [comment]
Hey! I will add the support by the end of this week.

**Comment by tjaadvd** [comment]
It works like a charm! Thank you for your work :)
