### ISSUE TITLE
Default Chat Usage is broken when you run into Token-Limit

### ISSUE THREAD

**Issue by dpeuscher** [carlrobertoh/CodeGPT#40]
When only using the chat-mode in the tool-view you cannot (easily?) create new chats. So at some point when you run inevitably in the token-limit (right now 4096 Tokens for GPT-3.5-turbo) the chat is dead
Suggestions:
- Add the ability to create new chats
- Add the ability to remove parts of the conversation in order to reduce the conversation size

**Comment by carlrobertoh** [comment]
Hi, thank you for the feature request.

Atm the only way to create a new session/chat is to use the editor menu actions which isn't ideal.

I like your suggestions and will try to deliver them in the upcoming days.

FYI, I'm also thinking of adding a remaining token count indicator.

**Comment by mournblade** [comment]
Hey thanks for responding quickly! Thanks for input, no sweat, looking forward to future updates!

**Comment by wkj89** [comment]
> Hi @mournblade
> 
> Clicking on  "Ask ChatGPT" will clear your previous chat and starts a new session.
> 
> > One more thing, my "conversation history" has 2 rows now, but shouldn't I be able to delete them?
> 
> The "Conversation History" is relatively new feature and doesn't support deleting the items yet, I'm working on improving it.
> 
> Best regards

Sorry,I didn't see "Ask ChatGPT" ,no matter in "chat" or "Conversation History" .  Any other to clear or creat new conversation?

**Comment by carlrobertoh** [comment]
Hi @wkj89 

"Ask ChatGPT" or any other prompt is available from the editor menu. Right click anywhere on the editor -> CodeGPT -> Ask ChatGPT.

There's also a GIF in the repository's README section describing some of the features.

Best regards

**Comment by carlrobertoh** [comment]
> FYI, I'm also thinking of adding a remaining token count indicator.

Apparently the API doesn't return data usage in the stream mode. https://community.openai.com/t/usage-info-in-api-responses/18862/11

**Comment by carlrobertoh** [comment]
Hi, new conversations can be created from the toolwindow's toolbar menu now.
The feature was added in version 1.6.0.
Ability to remove parts of the conversation is still in TODO, not sure when I'll get to it tho.
