### ISSUE TITLE
Api token resets after restart PhpStorm client

### ISSUE THREAD

**Issue by timoheutsrs** [carlrobertoh/CodeGPT#411]
### What happened?

Every time, the PHPstorm client (our organization works with the Jetbains gateway) restarts, the API token must be entered again.

### Steps to reproduce

- Go via Jetbrains gateway to PHPStorm Client
- Ask question to CodeGPT, notice message API token not provided
- Add token in settings
- Ask the same question again, an answer will be given
- Restart the PhpStorm client
- Aks a question, notice that again the Api Token must be provided

### CodeGPT version

2.5.0

### Operating System

Linux

**Comment by SamuelBohumel** [comment]
Hello, same problem here

**Comment by reneleonhardt** [comment]
@timoheutsrs @SamuelBohumel Thank you for reporting, can you tell us what services you selected and configured with an API token?

**Comment by timoheutsrs** [comment]
[cid:06982262-9407-4fb6-be79-54477aa248c8]
This is my config, ofcourse I readded the api key for now. But after each restart of the phpStorm api client the key is cleared

Met vriendelijke groet,
​
TimoHeuts
Developer
***@***.***
+31 6 236 594 53
________________________________
Van: Rene Leonhardt ***@***.***>
Verzonden: vrijdag 12 april 2024 20:31
Aan: carlrobertoh/CodeGPT ***@***.***>
CC: Timo Heuts | Retail Solutions ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [carlrobertoh/CodeGPT] Api token resets after restart PhpStorm client (Issue #411)


@timoheutsrs<https://github.com/timoheutsrs> @SamuelBohumel<https://github.com/SamuelBohumel> Thank you for reporting, can you tell us what services you selected and configured with an API token?

**Comment by carlrobertoh** [comment]
It should be fixed in the latest version. Please reopen the ticket if it's still reproducible.

**Comment by timoheutsrs** [comment]
Yes its fixed, thanks! Appreciate it!

Met vriendelijke groet,
​
TimoHeuts
Developer
***@***.***
+31 6 236 594 53
________________________________
Van: Carl-Robert ***@***.***>
Verzonden: dinsdag 23 april 2024 13:32
Aan: carlrobertoh/CodeGPT ***@***.***>
CC: Timo Heuts | Retail Solutions ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [carlrobertoh/CodeGPT] Api token resets after restart PhpStorm client (Issue #411)


It should be fixed in the latest version. Please reopen the ticket if it's still reproducible.
