### ISSUE TITLE
Something went wrong. Please try again later.

### ISSUE THREAD

**Issue by BarryYang1** [carlrobertoh/CodeGPT#42]
1.5.2版本的，已经设置了key，但是问的时候返回Something went wrong. Please try again later.

**Comment by BarryYang1** [comment]
解决了，加个代理就可以

**Comment by bny64** [comment]
> 解决了，加个代理就可以

代理是什么？

**Comment by BarryYang1** [comment]
> > 解决了，加个代理就可以
> 
> 代理是什么？

VPN啊，然后在idea里面配置VPN端口号，Host name就是VPN的地址，比如安在本机就是127.0.0.1
