### ISSUE TITLE
Keyboard shortcut for hiding CodeGPT window

### ISSUE THREAD

**Issue by iosifnicolae2** [carlrobertoh/CodeGPT#421]
### Describe the need of your request

We would like to be able to hide CodeGPT window.

**Comment by carlrobertoh** [comment]
Hi, this can already be achieved by setting the key in Settings | Keymap.

<img width="892" alt="keymap" src="https://github.com/carlrobertoh/CodeGPT/assets/15891408/c838257e-9d43-4f64-ac2c-17cbbaee54c1">
