### ISSUE TITLE
Read file

### ISSUE THREAD

**Issue by Soufdsfe65w** [carlrobertoh/CodeGPT#428]
### Describe the need of your request

Hi author, is it possible to add a function that reads a file or references a file?
Optimised token formatting to recognise replicated IDEA token formats.

**Comment by carlrobertoh** [comment]
Hey, wdym by a function that reads a file or references a file?
Would this work?

<img width="815" alt="Screenshot 2024-03-28 at 12 44 13" src="https://github.com/carlrobertoh/CodeGPT/assets/15891408/c323999a-d477-4123-b58b-f671c3c39027">

`Right-click on a project file/folder` -> `CodeGPT` -> `Include in Context...`

**Comment by Soufdsfe65w** [comment]
Hi, what I mean is that it's possible to add a reference/context reading
feature?

Carl-Robert ***@***.***> 于2024年3月28日周四 18:47写道：

**Comment by WilliamEddy** [comment]
Thanks @carlrobertoh! I had this exact same question and your answer provided what I needed. I was expecting this option to be in the context menu for the currently open file similar to how github copilot has it. 
<img width="641" alt="image" src="https://github.com/carlrobertoh/CodeGPT/assets/3341467/d9fa8563-0334-4e50-9d63-ebfb80cf7e1f">

copilot context menu for reference
<img width="529" alt="image" src="https://github.com/carlrobertoh/CodeGPT/assets/3341467/f68366e5-ce16-4f41-9a22-4fe6b8e5f040">


@Soufdsfe65w just to reiterate what @carlrobertoh had said, right click on the left side in the project view for this option.
<img width="618" alt="image" src="https://github.com/carlrobertoh/CodeGPT/assets/3341467/17ad27d7-d01b-4f71-b5a7-f26dea7dd342">

**Comment by Soufdsfe65w** [comment]
Thanks, I saw it. Special thanks.

**Comment by carlrobertoh** [comment]
@WilliamEddy Nice, I didn't think of that. I'll add it to the editor's context menu as well. 👍
