### ISSUE TITLE
Placeholders for SystemPrompt, CommitPrompt

### ISSUE THREAD

**Issue by rwese** [carlrobertoh/CodeGPT#432]
### Describe the need of your request

I want to make my prompts aware of my branch, project, and other Metadata the IDE does provide and place it in my custom-prompts.

For example:
```
{{BRANCH}}
{{PROJECT}}
{{CURRENT_DATE}}
```

So i am able to prompt the model to use the information.

`Current_Branch: {{BRANCH}}`

Create a commit message based on this diff, extract the TicketNumber `<JIRA-xxxx>` and set `[TicketNumber] <commit message>`

### Proposed solution

Add a new function to process placeholders when getting the stored prompts.

new: `java/ee/carlrobert/codegpt/util/PlaceholderUtil.java`

modify:

- `ee.carlrobert.codegpt.settings.configuration.ConfigurationState#getSystemPrompt`
- `ee.carlrobert.codegpt.settings.configuration.ConfigurationState#getCommitMessagePrompt`

**Comment by rwese** [comment]
Please let me know if this will work for you and I will try to implement it.

**Comment by carlrobertoh** [comment]
Sure, this sounds like a good idea. I assume those placeholders will be configured inside a table?
