### ISSUE TITLE
Couldn't sign in [intellij] (CodeGPT v1.6.1)

### ISSUE THREAD

**Issue by nuth-vireak** [carlrobertoh/CodeGPT#44]
![image](https://user-images.githubusercontent.com/66857698/225968893-007b6c01-657f-4a76-9a05-2747c3f9e234.png)

**Comment by carlrobertoh** [comment]
Hi @nuth-vireak 

Unfortunately Google nor Microsoft login isn't possible due their own security reasons.

FYI: The plugin is built around the completion's API and I'd suggest you to use the Chat tab instead.

Best regards
