### ISSUE TITLE
High CPU usage with v2.6.0

### ISSUE THREAD

**Issue by fishermans** [carlrobertoh/CodeGPT#446]
### What happened?

After updating from 2.5.1 to 2.6.0 on Intellij IDEA Ultimate 2024.1, the CPU usage is high even on idle. The fans are running on highest speed all the time on my MacBook Pro 2020 Intel. This is also happening when I am simply launching IntelliJ and opening any of my projects without further actions. Cache cleanup did not help.

All is working fine after I downgraded to 2.5.1 again.

Any suggestions?

### CodeGPT version

2.6.0

### Operating System

macOS

**Comment by carlrobertoh** [comment]
Hey, without a relevant thread dump, it's hard to say. One possible option is that the file watcher CodeGPT uses to check for new screenshots is taking a toll on your CPU. Try disabling the feature and see if it makes any difference.

<img width="613" alt="Screenshot 2024-04-11 at 11 50 37" src="https://github.com/carlrobertoh/CodeGPT/assets/15891408/6e2f27a2-240d-45c0-87e0-3ba64f104e85">

**Comment by fishermans** [comment]
Thank you very much. It seems to work now.

BTW: I was not able to disable this setting. The "Apply" button remained grayed out until I unchecked at least one of the other options as well. So I had to disable screenshot and method name lookup suggestions to be able to apply it. I then re-enabled the method name option again.

For testing purposes, I removed all CodeGPT settings files from the options folder and tried again with the default settings, but this behavior persisted.

**Comment by carlrobertoh** [comment]
I'm glad you got it working!
I'll keep the ticket open until I find a fix for it and in case anyone else runs into the same issue.

**Comment by reneleonhardt** [comment]
> BTW: I was not able to disable this setting. The "Apply" button remained grayed out until I unchecked at least one of the other options as well. So I had to disable screenshot and method name lookup suggestions to be able to apply it. I then re-enabled the method name option again.
> 
> For testing purposes, I removed all CodeGPT settings files from the options folder and tried again with the default settings, but this behavior persisted.

@fishermans There was a bug in the settings, thank you for reporting so I could fix it, please try again in the next release after 2.6.0.

**Comment by carlrobertoh** [comment]
This issue should be fixed in the new version 2.6.1. Please reopen the ticket if it is still reproducible.

**Comment by kaorukobo** [comment]
@carlrobertoh Thanks for trying to fix this.

Unfortunately, the problem remains with Code GPT 2.6.2-241 + IDEA 2024.1. FileAltertionObserver takes the CPU over if I turn on "check for new screenshots" option.

![img 2024-04-16 10 45 33](https://github.com/carlrobertoh/CodeGPT/assets/475350/0a590108-ddf9-4117-b6fe-cf27868ceb55)
![img 2024-04-17 12 04 08](https://github.com/carlrobertoh/CodeGPT/assets/475350/c61f106c-9ab8-499e-b748-ee5604d307a8)

**Comment by kaorukobo** [comment]
> The "Apply" button remained grayed out until I unchecked at least one of the other options as well.

This problem also remains with 2.6.2-241.

**Comment by kaorukobo** [comment]
My desktop has only 62 entries. But if the folder is scanned recursively, there are total 10700 entries.

Is FileAltertionObserver scanning my desktop recursively...? 
even though it is enough to scan only under-root entries to look for new screenshot files.

**Comment by carlrobertoh** [comment]
The `FileAlterationMonitor` runs every 0.5 seconds and should only listen for new files, although I've seen some anomalies when making alterations to existing files.

https://github.com/carlrobertoh/CodeGPT/blob/master/src/main/kotlin/ee/carlrobert/codegpt/FileWatcher.kt

**Comment by carlrobertoh** [comment]
> This problem also remains with 2.6.2-241.

Weird, I thought we fixed this.

**Comment by fishermans** [comment]
Maybe, you should go for WatchService instead of the apache implementation. FileAlterationObserver is calling Files.list each time to compare for changes as per https://stackoverflow.com/questions/32887364/apache-commons-io-file-monitoring-vs-jdk-watchservice.

**Comment by kaorukobo** [comment]
> Weird, I thought we fixed this.

@carlrobertoh @reneleonhardt 
I think `ConfigurationState.equals` should be also fixed. There is no comparison for `checkForNewScreenshots`:
https://github.com/carlrobertoh/CodeGPT/blob/92d9d5ee20bfc66e69635d44e3b3db326e7ec48e/src/main/java/ee/carlrobert/codegpt/settings/configuration/ConfigurationState.java#L122

**Comment by carlrobertoh** [comment]
This issue should be fixed in the latest version.

@kaorukobo @reneleonhardt many thanks! 💯

**Comment by kaorukobo** [comment]
Thank you for fixing this!
I have checked that the two problems went away in 2.6.3.
