### ISSUE TITLE
Error: report error when activate

### ISSUE THREAD

**Issue by UniMars** [carlrobertoh/CodeGPT#45]
version:1.6.1
It happens every time
report says:

> Unable to retrieve credit info
> 
> java.net.ConnectException: Failed to connect to api.openai.com/199.96.61.1:443
> 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
> 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
> 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
> 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
> 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
> 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
> 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
> 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
> 	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
> 	at ee.carlrobert.codegpt.client.Client.getCreditGrants(Client.java:77)
> 	at ee.carlrobert.codegpt.ide.toolwindow.chat.actions.UsageToolbarLabelAction.createCustomComponent(UsageToolbarLabelAction.java:19)
> 	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.createCustomComponent(ActionToolbarImpl.java:464)
> 	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.getCustomComponent(ActionToolbarImpl.java:439)
> 	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.fillToolBar(ActionToolbarImpl.java:390)
> 	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.actionsUpdated(ActionToolbarImpl.java:1350)
> 	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImplFastTrack(ActionToolbarImpl.java:1301)
> 	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImpl(ActionToolbarImpl.java:1267)
> 	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$1.updateActionsImpl(ActionToolbarImpl.java:211)
> 	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyUpdateRunnable.run(ToolbarUpdater.java:152)
> 	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.updateActions(ToolbarUpdater.java:68)
> 	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.java:1246)
> 	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.java:1231)
> 	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.addNotify(ActionToolbarImpl.java:271)
> 	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
> 	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4847)
> 	at java.desktop/java.awt.Container.addImpl(Container.java:1150)
> 	at java.desktop/java.awt.Container.add(Container.java:1001)
> 	at com.intellij.openapi.wm.impl.content.ToolWindowContentUi.ensureSelectedContentVisible(ToolWindowContentUi.java:308)
> 	at com.intellij.openapi.wm.impl.content.ToolWindowContentUi$1.selectionChanged(ToolWindowContentUi.java:194)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:120)
> 	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:85)
> 	at jdk.proxy1/jdk.proxy1.$Proxy104.selectionChanged(Unknown Source)
> 	at com.intellij.ui.content.impl.ContentManagerImpl.fireSelectionChanged(ContentManagerImpl.java:621)
> 	at com.intellij.ui.content.impl.ContentManagerImpl.addSelectedContent(ContentManagerImpl.java:432)
> 	at com.intellij.ui.content.impl.ContentManagerImpl$2.run(ContentManagerImpl.java:520)
> 	at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContent(ContentManagerImpl.java:536)
> 	at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContentCB(ContentManagerImpl.java:485)
> 	at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContentCB(ContentManagerImpl.java:475)
> 	at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContentCB(ContentManagerImpl.java:559)
> 	at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContent(ContentManagerImpl.java:564)
> 	at com.intellij.ui.content.impl.ContentManagerImpl.doAddContent(ContentManagerImpl.java:201)
> 	at com.intellij.ui.content.impl.ContentManagerImpl.addContent(ContentManagerImpl.java:171)
> 	at ee.carlrobert.codegpt.ide.toolwindow.ProjectToolWindowFactory.addContent(ProjectToolWindowFactory.java:50)
> 	at ee.carlrobert.codegpt.ide.toolwindow.ProjectToolWindowFactory.createToolWindowContent(ProjectToolWindowFactory.java:25)
> 	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:543)
> 	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:522)
> 	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:1009)
> 	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:946)
> 	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl$default(ToolWindowManagerImpl.kt:932)
> 	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.registerToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:1116)
> 	at com.intellij.toolWindow.ToolWindowSetInitializer.createAndLayoutToolWindows$registerToolWindows(ToolWindowSetInitializer.kt:134)
> 	at com.intellij.toolWindow.ToolWindowSetInitializer.createAndLayoutToolWindows(ToolWindowSetInitializer.kt:160)
> 	at com.intellij.toolWindow.ToolWindowSetInitializer.access$createAndLayoutToolWindows(ToolWindowSetInitializer.kt:46)
> 	at com.intellij.toolWindow.ToolWindowSetInitializer$initUi$3.invokeSuspend(ToolWindowSetInitializer.kt:106)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> 	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:194)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
> 	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:454)
> 	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
> 	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
> 	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
> 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
> 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
> 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
> 	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
> 	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
> 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
> Caused by: java.net.ConnectException: Connection timed out: no further information
> 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
> 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
> 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
> 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
> 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
> 	at java.base/java.net.Socket.connect(Socket.java:633)
> 	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
> 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
> 	... 95 more
>

**Comment by carlrobertoh** [comment]
Hi, thanks for reporting.

Is the plugin reacting at all?
The error might be in the proxy, i'll try to reproduce it locally.
