### ISSUE TITLE
Many Crashes on Webstorm 

### ISSUE THREAD

**Issue by mgoldenberg-nv** [carlrobertoh/CodeGPT#452]
### What happened?

I have Webstorm WebStorm 2024.1 
and the plugin making me a lot of crahses

### Steps to reproduce

just work with webstorm running a next js/react project

### CodeGPT version

2.6.0-241

### Operating System

None

**Comment by carlrobertoh** [comment]
Thank you for reporting!

I have decided to remove version 2.6.0 from the marketplace due to several other similar reports. I will try to reproduce the issue and publish a fix asap.

**Comment by mgoldenberg-nv** [comment]
@carlrobertoh im trying with older version [2.5.1]
but I still see in market place the 2.6 version, it looks like critical issue hope you will fix it soon

**Comment by mgoldenberg-nv** [comment]
@carlrobertoh btw I can send you the crash reports I sent to Webstorm when I opened the bug for them and they told me its in one of the plugins

**Comment by mgoldenberg-nv** [comment]
https://youtrack.jetbrains.com/issue/JBR-6919
you can see here in attachments my logs when it crashes
