### ISSUE TITLE
Config not saving API key

### ISSUE THREAD

**Issue by loevstroem** [carlrobertoh/CodeGPT#457]
### What happened?

When you set the API key for the Anthropic Service under Settings | Tools | CodeGPT and then restart PHPStorm, the API key resets to null. This suggests it's either not saving correctly or resetting upon reload.

### CodeGPT version

2.6.0-241

### Operating System

macOS

**Comment by QuadStingray** [comment]
Same on Custom Open Ai Configuration. 

Workaround is to change variable for authentication on header from variable to your api key.

**Comment by reneleonhardt** [comment]
I hope my contribution https://github.com/carlrobertoh/CodeGPT/pull/456 will be merged, it should solve all non-persisted API key problems 😄
Kudos to @QuadStingray for finding a workaround in the mean time, at least for Custom OpenAI 👍

**Comment by kriit24** [comment]
same thing in 2026
