### ISSUE TITLE
Allow extension to index a local folder for generate solutions from it.

### ISSUE THREAD

**Issue by colinquek** [carlrobertoh/CodeGPT#467]
### Describe the need of your request

For example i have a folder C:\terraform_modules. This folder contains some in house templates we use to generate terraform scripts.
Now say I ask Claude to give me a set of VPC and subnet terraform scripts, based on what we have defined in C:\terraform_modules

Or another way if i have a folder C:\inhouse_bash. This folder contains some bash .sh files that we frequently.
Now I want to ask Claude to give me a main.sh file to accomplish certain tasks, based on what is available inside C:\inhouse_bash.

Can it be done?

**Comment by carlrobertoh** [comment]
Hey,

Would [referencing a folder](https://github.com/carlrobertoh/CodeGPT?tab=readme-ov-file#reference-files) and modifying the default prompt work? The only missing part is saving the generated content to a file.

Furthermore, I'm working on building CodeGPT Agents, which should cover scenarios where AI needs access to files, the current editor, VCS history, etc., but it's hard to say when I'll make it available to the public.

**Comment by colinquek** [comment]
Hi @carlrobertoh , thanks for the quick reply, let me try to referencing the folder. 
Thanks for sharing that the Agents should cover the scenarios, i will await for further news and use them when they are available.

Cheers.
:)

**Comment by colinquek** [comment]
oh yes forgot to close the request.
