### ISSUE TITLE
This browser or app may not be secure.

### ISSUE THREAD

**Issue by cubeweb** [carlrobertoh/CodeGPT#47]
Great plugin!

One small issue, when I am trying to login with google in the Browser tab I get this error

Couldn’t sign you in
This browser or app may not be secure.
Try using a different browser. If you’re already using a supported browser, you can try again to sign in.

PhpStorm 2023.1 Beta

**Comment by carlrobertoh** [comment]
Hi @cubeweb 

Unfortunately Google nor Microsoft login isn't possible due their own security reasons. If you happen to know any reasonable workaround for it then I'm all ears :) 

FYI: The plugin is built around the completion's API and I strongly suggest using the Chat tab instead.

Best regards

**Comment by cubeweb** [comment]
Hi, I do use the chat tab and works very nice. I just thought to try the browser tab. No big deal for me at least. Again great work!

**Comment by carlrobertoh** [comment]
Glad to hear, thank you!
