### ISSUE TITLE
 Could you explain the reason for using a proxy? 

### ISSUE THREAD

**Issue by shanzhongxu** [carlrobertoh/CodeGPT#471]
### Describe the need of your request

https://github.com/carlrobertoh/CodeGPT/issues/340
Hello, I've also noticed this issue and have been tracing the source code, but I'm not sure why the proxy selector in IDEA does not default to the local network proxy. However, when I run tests, it can select the local proxy. Could you explain this to me in more detail or offer some advice on where to look in the source code? @carlrobertoh

**Comment by carlrobertoh** [comment]
Hey, could you please clarify what you mean by "the proxy selector in IDEA does not default to the local network proxy"? Also, how did you run the tests with the local proxy? 

The proxy is used only when you have configure it in the settings.
https://github.com/carlrobertoh/CodeGPT/blob/master/src/main/java/ee/carlrobert/codegpt/completions/CompletionClientProvider.java#L100

**Comment by shanzhongxu** [comment]
Thank you for your reply. My computer uses ClashX, and when I do not set a proxy service in the plugin, using the plugin's features to call OpenAI results in a "no host" exception. However, when I use the test method with the same OkHttpClient package (okhttp3), it works fine. I am not quite clear on what processing is done during this call.  
<img width="1098" alt="截屏2024-04-18 21 13 04" src="https://github.com/carlrobertoh/CodeGPT/assets/21250418/1e5b677b-7c91-43bb-b92a-6a21fe208582">

**Comment by shanzhongxu** [comment]
The issue might be because IntelliJ IDEA does not use the system proxy in development and testing environments. When no proxy is set, the HttpClient's ProxySelector uses IntelliJ's internal package, which is controlled by IDEA.
