### ISSUE TITLE
How to connect phpstorm to ollama?

### ISSUE THREAD

**Issue by it-can** [carlrobertoh/CodeGPT#493]
### What happened?

I have ollama installed and llama3 running on my mac, http://127.0.0.1:11434   , can also connect to it in OpenWebUI. How do i connect phpstorm to this?

this doesnt work

![Scherm­afbeelding 2024-04-22 om 17 06 03](https://github.com/carlrobertoh/CodeGPT/assets/644288/e841f566-823a-4c87-b7c0-ff89007d55b4)

### CodeGPT version

2.6.3-241

### Operating System

macOS

**Comment by carlrobertoh** [comment]
Hi, please use the Custom OpenAI Service with the Ollama template to connect with CodeGPT

**Comment by it-can** [comment]
doesnt seem to work...

![Scherm­afbeelding 2024-04-22 om 17 33 54](https://github.com/carlrobertoh/CodeGPT/assets/644288/2e0db5c5-b55f-4777-8c84-59c2ba5cbad6)
![Scherm­afbeelding 2024-04-22 om 17 34 11](https://github.com/carlrobertoh/CodeGPT/assets/644288/fc0d252e-bcd9-44c9-b833-de4949854b34)

**Comment by taylorcoffelt** [comment]
![image](https://github.com/carlrobertoh/CodeGPT/assets/690213/5280f1b8-3809-4014-85b5-2cfbc50f2ab8)
You'll have to change model specified in the body of the requests to llama3
