### ISSUE TITLE
Problems with code completion using custom openai service (ollama)

### ISSUE THREAD

**Issue by samyIO** [carlrobertoh/CodeGPT#514]
### What happened?

In Pycharm 2023.3.4 i get an error message for every key i press when writing code.
![msg-too-short](https://github.com/carlrobertoh/CodeGPT/assets/65492678/87e4add1-c657-4494-b0ff-2f1e37bbb4ea)

here are the configs i use:

![completion](https://github.com/carlrobertoh/CodeGPT/assets/65492678/31862bb5-5d69-4f25-9574-809029edc1c1)

Any idea?

### CodeGPT version

2.6.3-233

### Operating System

Windows

**Comment by PhilKes** [comment]
You can not use the `/v1/chat/completions` API of Ollama for code-completions, you would need an OpenAI compatible `/v1/completions` API, which Ollama does not yet include.
https://github.com/carlrobertoh/CodeGPT/pull/510 will introduce Ollama as a high-level service and enable code-completions with the native Ollama API.
Same problem as in https://github.com/carlrobertoh/CodeGPT/issues/517
