### ISSUE TITLE
Enter Chinese garbled characters in the text box for entering questions.

### ISSUE THREAD

**Issue by leter** [carlrobertoh/CodeGPT#53]
in the IntelliJ IDEA

**Comment by leter** [comment]
![微信图片_20230330103712](https://user-images.githubusercontent.com/13078495/228716979-ea6fcd2e-c809-448a-b0b2-87567e85ffe4.png)

**Comment by carlrobertoh** [comment]
Are you able to copy-paste the characters into the textbox?
<img width="555" alt="Screen Shot 2023-03-30 at 22 48 27" src="https://user-images.githubusercontent.com/15891408/228972172-e139c3a1-9a9f-4cb4-8aa0-8acc066fcab5.png">
