### ISSUE TITLE
gpt-4o support

### ISSUE THREAD

**Issue by GiGurra** [carlrobertoh/CodeGPT#547]
### Describe the need of your request

Please make it possible to select OpenAI's latest model, gpt-4o.

**Comment by GiGurra** [comment]
@carlrobertoh How does this work with new plugin releases, do you need to wait for jetbrains to check this new version before it becomes available in the marketplace?

**Comment by carlrobertoh** [comment]
@GiGurra Correct. I need to wait for their verification and approval process, which might take up to 2 business days.
