### ISSUE TITLE
请问该如何完成code completion功能的配置？

### ISSUE THREAD

**Issue by YangWaldon** [carlrobertoh/CodeGPT#574]
### What happened?

When testing the code completion feature, it always shows an error. The screenshot of the error is as follows:

### Steps to reproduce

![image](https://github.com/carlrobertoh/CodeGPT/assets/49675185/eb6970f5-e995-4470-b14b-ed19faa2f48f)
![image](https://github.com/carlrobertoh/CodeGPT/assets/49675185/c96c09a1-b304-4f29-909e-dcea99adbc7f)

### CodeGPT version

2.7.1-241

### Operating System

Windows

**Comment by PhilKes** [comment]
I am guessing the "ezchat" API is some sort of Proxy for OpenAI's API?
If you are trying to use `gpt-3.5-turbo-instruct` you should use the `/v1/completions`, not `/v1/chat/completions` is compatible with that model for code-completions.
You look at the `Azure OpenAI` Preset template for the body:

![image](https://github.com/carlrobertoh/CodeGPT/assets/39240633/2685ccb6-70bd-4d82-b0ea-8379b72af4fc)

**Comment by YangWaldon** [comment]
> gpt-3.5-turbo-instruct

Thank you, I solved my problem according to your instructions, but what do you mean by Azure OpenAI?

**Comment by PhilKes** [comment]
> > gpt-3.5-turbo-instruct
> 
> Thank you, I solved my problem according to your instructions, but what do you mean by Azure OpenAI?

Good to hear that its working for you now.
I just wanted to point out that you can look at the `Azure OpenAI` Preset template to see how to set the Body for `/v1/completions`
![image](https://github.com/carlrobertoh/CodeGPT/assets/39240633/f2e388d2-8241-4eed-80e5-5ac5f5caeb4c)

**Comment by YangWaldon** [comment]
> > > gpt-3.5-turbo-instruct
> > 
> > 
> > Thank you, I solved my problem according to your instructions, but what do you mean by Azure OpenAI?
> 
> Good to hear that its working for you now. I just wanted to point out that you can look at the `Azure OpenAI` Preset template to see how to set the Body for `/v1/completions` ![image](https://private-user-images.githubusercontent.com/39240633/334156150-f2e388d2-8241-4eed-80e5-5ac5f5caeb4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MjUyNjcsIm5iZiI6MTcxNjgyNDk2NywicGF0aCI6Ii8zOTI0MDYzMy8zMzQxNTYxNTAtZjJlMzg4ZDItODI0MS00ZWVkLTgwZTUtNWFjNWY1Y2FlYjRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDE1NDkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3MzU4MTRlMjJmN2VmY2I3NDE3ZGU5Nzg2ZmM5ZjRhMWY3YjYzYTZjNjU2ZDRjYmMwNTJmYjBlMjM3MDEyMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tCxoD-Wy-qpANDUjqJ0in7vOJ9HhK2VDwnCpQT4G3_8)

I see what you mean. Thank you again.
