### ISSUE TITLE
How can I log in to You.com? Can you provide a complete set of instructions for the process?

### ISSUE THREAD

**Issue by YangWaldon** [carlrobertoh/CodeGPT#575]
### What happened?

When I tried to log in to You.com with my Google account, it said to use Stach······ Why does it have to be so complicated?

### CodeGPT version

2.7.1-241

### Operating System

Windows

**Comment by carlrobertoh** [comment]
You.com support will be removed in the near future. Please consider [CodeGPT provider](http://codegpt.ee/) as an alternative option.
