### ISSUE TITLE
unable to load model when using ollama(local) provider

### ISSUE THREAD

**Issue by litaolaile** [carlrobertoh/CodeGPT#578]
### What happened?

i can not load model,but the address has exist ollama model,my friend can load model with same address
![image](https://github.com/carlrobertoh/CodeGPT/assets/74705347/41726b7f-8dd5-4dc9-9808-b399024abe27)
![image](https://github.com/carlrobertoh/CodeGPT/assets/74705347/a65c378d-0b74-493a-88f6-84882a724823)
the version of idea is 
![image](https://github.com/carlrobertoh/CodeGPT/assets/74705347/d7ea1eef-00e2-45a5-b92d-536e7a1f4ff1)

### CodeGPT version

2.7.1-233

### Operating System

Windows

**Comment by PhilKes** [comment]
I think this is probably due to the trailing "/" in your `Base host`. Try to remove it and test it again.
I will create a PR to mitigate this annoying problem

**Comment by litaolaile** [comment]
not useful by remove trailing slashes
