### ISSUE TITLE
GPT4.0 使用提示The model: `gpt-4` does not exist

### ISSUE THREAD

**Issue by zuilintan** [carlrobertoh/CodeGPT#58]
![image](https://user-images.githubusercontent.com/34953840/227165735-7d3b3000-1493-49f6-a245-e12775d2aba4.png)
已可试用GPT4.0

**Comment by zuilintan** [comment]
但
![image](https://user-images.githubusercontent.com/34953840/227166011-ff97f906-ca70-49a4-86cb-4a4f052dacda.png)
![image](https://user-images.githubusercontent.com/34953840/227166057-30e3ac2b-2296-4633-b92e-34a2356fdd21.png)

**Comment by carlrobertoh** [comment]
您是否注册了 GPT-4 候补名单?
https://openai.com/waitlist/gpt-4-api

**Comment by spyro2000** [comment]
Same here (have plus subscription):
![image](https://user-images.githubusercontent.com/8479925/227861060-34c5b451-3d89-4fd4-98cb-dda7dde39c4e.png)

![image](https://user-images.githubusercontent.com/8479925/227861104-f0cba9d3-329a-4561-b698-d4fdf0aff7e0.png)
