### ISSUE TITLE
Option to disable code completions

### ISSUE THREAD

**Issue by mrsimpson** [carlrobertoh/CodeGPT#588]
### Describe the need of your request

When working with the plugin, completions are mostly much less good than the IDE's inbuilt suggestions. 

### Proposed solution

As also proposed in a review: Just add an option to the settings to not trigger completion

### Additional context

From another review

> I want to disable 2 options:
> "enable code completions" because I'm happy with IDE completions, I don't need this
> "check for new screenshots", as I don't want this plugin to touch any files on my laptop
> And I can't! During this month, I've disabled them at least 10 times, and they are returning back again and again. It becomes very annoying.

**Comment by mrsimpson** [comment]
Found the option myself: It's configured per provider, which absolutely makes sense 👍 
<img width="915" alt="Bildschirmfoto 2024-06-03 um 15 15 46" src="https://github.com/carlrobertoh/CodeGPT/assets/17176678/8a1fdd32-1b9c-44b0-91b1-be3ac129b421">
Well done, @carlrobertoh

**Comment by Coronal-Halo** [comment]
@mrsimpson Where can I pull up this interface to change this setting?

**Comment by mrsimpson** [comment]
Just in the usual IDE settings (`Cmd+,` on Mac)
