### ISSUE TITLE
IntelliJ Plugin Causes IntelliJ to freeze when selecting "Generate" for commit message.

### ISSUE THREAD

**Issue by GaryStimson** [carlrobertoh/CodeGPT#589]
### What happened?

I'm using local Ollama with Code Gemma model. This works fine sending chats and code explain etc. However when I select generate for the check in submit it simply crashes and I cannot recover. It just freezes the IDE.

### Steps to reproduce

On latest release of ItelliJ Idea, install CodeGPT plugin and set up to use local LLM (Ollama) with Code Gemma or Mistral 7b models. Then go to check in some code (for SVN) and select the generate button on the prompt. Note how the UI freezes and does not recover.

### CodeGPT version

1.16.0

### Operating System

Windows

**Comment by xaapro** [comment]
same thing. open ai is used

**Comment by carlrobertoh** [comment]
Commit message generation has undergone many improvements. Please reopen the ticket if the issue still persists.
