### ISSUE TITLE
Find usages window no longer appears

### ISSUE THREAD

**Issue by nadia-tarashkevich** [carlrobertoh/CodeGPT#592]
### What happened?

The IDE successfully detects that a symbol is used n times. 

Unfortunately, it's not possible to show the usage of the symbol. The dialog won't appear, regardless of the way to open it: 

by using the shortcut Opt+F7, by using the menu entry or by clicking on the symbol. The dialog stopped working on 2024.1 and still fails on 2024.1.2.

Disabling CodeGPT plugin solved the issue

### Steps to reproduce

Press Opt+F7 on any symbol

### CodeGPT version

7

### Operating System

macOS

**Comment by reneleonhardt** [comment]
Hello @nadia-tarashkevich thank you for reporting, I can't really see how CodeGPT could stop the Find dialog from working without an exception being thrown in the log.
* Could you make a screenshot of what you mean by symbol occurence working? That's not the Find dialog.
* There is no CodeGPT 7, could you specify the full plugin version you're using? Mine is `2.8.0-241.1` for example.
* What IDE are you using? The latest version is `2024.1.3`, could you try that and the last `2023.3.7` to see if either solves your problem.

**Comment by sidler** [comment]
@reneleonhardt I think you may close this issue. I was in contact with @nadia-tarashkevich regarding this problem. There was a problem in phpstorm causing the Find dialog to stop opening and one way to reproduce it was to install / uninstall the codegpt plugin. But: the problem itself was related to a set of corrupted phpstorm preferences and not the codegpt plugin. There: please close as not reproducible.

**Comment by reneleonhardt** [comment]
Thank you very much for your feedback, @carlrobertoh please close this issue.
