### ISSUE TITLE
Commit message templates not working in 2.8.0

### ISSUE THREAD

**Issue by Bikkies** [carlrobertoh/CodeGPT#593]
### What happened?

After upgrading to 2.8.0-241.1 in phpstorm 2024.1.2, the {BRANCH_NAME} template no longer works. It just shows `BRANCH-UNKNOWN` to the LLM. Downgrading to 2.7.1-241 solves the issue and correctly replaces the template with the branch name.

### Steps to reproduce

Include `{BRANCH_NAME}` in the Commit Message Template and test with verbose output on the LLM to see the input. On 2.8.0, it will be replaced to `BRANCH-UNKNOWN`. On 2.7.1 it will be correctly replaced with the branch name.

### CodeGPT version

2.8.0

### Operating System

Windows

**Comment by carlrobertoh** [comment]
This issue should be fixed in the latest release.
