### ISSUE TITLE
Codegpt occupies CPU resources

### ISSUE THREAD

**Issue by 478137607** [carlrobertoh/CodeGPT#598]
### What happened?

I found that the idea is not running at all, but it still consumes a lot of CPU. After troubleshooting, I found that there is a monitor that keeps scanning my desktop folder (with a lot of files), causing the idea to lag. Further investigation reveals that there is a listener in this FileAlterationObserver, which is: ee. carlrobert. codegt FileWatcher。  I think this should be internal to the plugin, but I don't understand why my desktop folder needs to be scanned.
idea:2022
![image](https://github.com/carlrobertoh/CodeGPT/assets/34698521/c5babe90-e39c-430c-9273-a4602ceb6043)

### CodeGPT version

2.6.2

### Operating System

Windows

**Comment by carlrobertoh** [comment]
Thanks for pointing that out!

The FileScanner is used to detect and automatically attach images to your chat sessions as they are created. I find this feature very handy, especially on macOS, where each screenshot appears on the desktop by default. 

<img width="381" alt="Screenshot 2024-06-24 at 11 59 22" src="https://github.com/carlrobertoh/CodeGPT/assets/15891408/aef06f5b-e87c-4c71-821f-8f04ac7f8c72">

If this is causing issues, you can toggle it off in the settings: **Tools > CodeGPT > Configuration > Check for new screenshots automatically**

**Comment by 478137607** [comment]
Thank you.
Turning off this option will eliminate the issue
