### ISSUE TITLE
Enter key doesn't work with "Code Edit" 

### ISSUE THREAD

**Issue by lurebat** [carlrobertoh/CodeGPT#602]
### What happened?

When using the new code edit screen, the enter and tab key don't work to actually submit the code - you have to user your mouse.

P.S it seems that custom models are not working for this feature - but it seems intended from the wording at the PR?

### CodeGPT version

2.8.2-241.1

### Operating System

Windows

**Comment by carlrobertoh** [comment]
Thank you for your feedback! I will fix the issues mentioned above in the next release.

Regarding support for other providers, this is mentioned in the recent blog post: https://codegpt.ee/blog/introducing-fast-edits

I have also updated the PR.
