### ISSUE TITLE
Unable to select model when using an Ollama backend.

### ISSUE THREAD

**Issue by flutas** [carlrobertoh/CodeGPT#606]
### What happened?

When using the Ollama backend, the ComboBox for selecting a model does not display models, instead only displaying "Loading..." indefinitely.

<img width="721" alt="image" src="https://github.com/carlrobertoh/CodeGPT/assets/52019318/5070aa1f-75c7-406a-bf38-7c69c991d6f1">

This was caused by #601, this change moved the ComboBox model update from being ran by `invokeLater` to `runInEdt`.

https://github.com/carlrobertoh/CodeGPT/blob/c55237b72b7fb87450317f30d8169c1e2d3efa95/src/main/kotlin/ee/carlrobert/codegpt/settings/service/ollama/OllamaSettingsForm.kt#L156

Reverting this to `invokeLater` fixes the issue, but I decided to open an issue rather than a PR, as I don't know the underlying rationale behind moving from `invokeLater` to `runInEdt`.

### Steps to reproduce

1. Install CodeGPT
2. Attempt to configure CodeGPT to use a Ollama backend.
3. Observe the models box not updating or displaying any models.

### CodeGPT version

2.8.2-241.1

### Operating System

macOS

**Comment by dejavuwl** [comment]
same here in Windows 11, models refresh keeps show 'loading' and 'Loading is not available, please select another model'
![image](https://github.com/carlrobertoh/CodeGPT/assets/19871560/8370e486-fd5f-4a98-ac51-1ad54fcb04ad)

**Comment by xiaoshyang** [comment]
我也遇到 了这个问题

**Comment by carlrobertoh** [comment]
Hi, thanks for reporting! I will take a look asap. The only difference is that `runInEdt` is using `ModalityState`, but I cannot see how this might affect this.
