### ISSUE TITLE
Include border in plugin window

### ISSUE THREAD

**Issue by dakotahNorth** [carlrobertoh/CodeGPT#61]
The image on the homepage shows border around the plugin window. 

![image](https://user-images.githubusercontent.com/7173343/227620706-87396433-6d12-4a57-8eda-94c652aba34b.png)

On the latest version of Intellij on a Mac, there is no border. 

<img width="319" alt="image" src="https://user-images.githubusercontent.com/7173343/227621043-f1214cef-10e6-4014-b760-2c03b024051f.png">

With the border view is a more polished look.

**Comment by carlrobertoh** [comment]
Hey, are you referring to the margins?
<img width="230" alt="Screen Shot 2023-03-25 at 11 53 57" src="https://user-images.githubusercontent.com/15891408/227715991-5965c8f8-5a09-4c7e-9ea7-a9a22c41795d.png">

**Comment by carlrobertoh** [comment]
Marking it as "WONT DO", tool window UI improvements are likely to be done by the end of this week.
Relates to #39

**Comment by carlrobertoh** [comment]
@dakotahNorth  https://github.com/carlrobertoh/CodeGPT/pull/64#issuecomment-1488372082
