### ISSUE TITLE
Unable to use OpenAI API key in Code edit feature

### ISSUE THREAD

**Issue by commi** [carlrobertoh/CodeGPT#613]
### What happened?

When submitting a code edit request it always sais i need a paid CodeGPT account, but i selected OpenAI as the provider. Use in a normal chat windows works as expected.

### CodeGPT version

2.8.2-241.1

### Operating System

Linux

**Comment by carlrobertoh** [comment]
The 'Fast Edits' feature is currently available only through CodeGPT's own provider. We plan to roll this out for other providers soon.

**Comment by commi** [comment]
Now also in normal Chat OpenAI-integration is broken:

Error message: `Incorrect API key provided: $CUSTOM_***********_KEY. You can find your API key at https://platform.openai.com/account/api-keys.`

**Comment by Ginotuch** [comment]
@carlrobertoh is there any update as to when this is planned, or an open issue we can track?

I'd love to use this at my work but we're unable to use any externally hosted LLMs due to security restrictions.
