### ISSUE TITLE
Name Suggestions how trigger when selected function name.

### ISSUE THREAD

**Issue by linpan** [carlrobertoh/CodeGPT#615]
### What happened?

Name Suggestions how trigger when selected function name.

### Relevant log output or stack trace

```shell
Name Suggestions how trigger when selected function name.
```

### Steps to reproduce

 Name Suggestions how trigger when selected function name.

### CodeGPT version

latest

### Operating System

macOS

**Comment by tbmc** [comment]
I got it working for Java in IntelliJ when I rename some simple functions, but I didn't have luck with PyCharm or Webstorm.
<img width="274" alt="image" src="https://github.com/user-attachments/assets/108ae8c0-497d-4e57-9681-f24c376468b1">

**Comment by hoobiee** [comment]
hi，Why have I never triggered anything? How do I trigger it?
