### ISSUE TITLE
Add support for DeepSeek API

### ISSUE THREAD

**Issue by sevenjay** [carlrobertoh/CodeGPT#622]
### Describe the need of your request

CodeGPT could integrate with the DeepSeek API to enhance its capabilities in coding.
The DeepSeek Coder V2 (236B) model gets the top score on aider’s code editing benchmark. https://aider.chat/docs/leaderboards/
DeepSeek API Doc https://platform.deepseek.com/api-docs/

**Comment by carlrobertoh** [comment]
Support for DeepSeek Coder V2 was introduced in version 2.10.0 for CodeGPT users. If you're not using the default provider,  then you can connect to the model via the Custom OpenAI provider.
