### ISSUE TITLE
Add spport for Fireworks.ai API

### ISSUE THREAD

**Issue by cantalupo555** [carlrobertoh/CodeGPT#639]
### Describe the need of your request

Hello, would it be possible to add support for the Fireworks.ai API?

**Comment by carlrobertoh** [comment]
Hi

Fireworks API can already be used via Custom OpenAI provider:

<img width="967" alt="fireworks" src="https://github.com/user-attachments/assets/464c693a-d94a-48bc-b4fc-4e292dcbf4b4">

**Comment by cantalupo555** [comment]
Thank you very much for the quick response.
