### ISSUE TITLE
When you paste multiline text, it's omit new lines at all.

### ISSUE THREAD

**Issue by n0isy** [carlrobertoh/CodeGPT#640]
### What happened?

Copy text from code window:
```
a
b
c
```
Paste it in CodeGPT chat window:
```
a b c
```
![изображение](https://github.com/user-attachments/assets/c046b396-eb7c-4996-aa89-93c510d27795)

### CodeGPT version

2.8.5-241.1

### Operating System

Windows

**Comment by n0isy** [comment]
Any updates?

**Comment by carlrobertoh** [comment]
Thanks for reporting! I'll try to fix it in the next release.
