### ISSUE TITLE
Response in Chat isn't displayed during generation until it's finished

### ISSUE THREAD

**Issue by scscgit** [carlrobertoh/CodeGPT#646]
### What happened?

When using this plugin, model's response in the Chat tab displays empty response until AI completes the entire message, unlike any other chat clients where each new incoming token is immediately displayed.
![image](https://github.com/user-attachments/assets/4a8ecba9-5b29-46a8-8a5e-fecec023386b)
With slower local models (Ollama), in practice this makes plugin's chat unusable.

### CodeGPT version

2.9.0-241.1

### Operating System

Windows

**Comment by carlrobertoh** [comment]
How are you connecting to Ollama? It sounds like the `stream` request parameter is set to false.

**Comment by scscgit** [comment]
I don't see any settings

![image](https://github.com/user-attachments/assets/fe439254-6bf0-445d-918a-4bbf4375e6cf)
![image](https://github.com/user-attachments/assets/83b42c81-37ac-4d66-8a92-754c96921b63)

**Comment by carlrobertoh** [comment]
Hmm, if you're connecting via Ollama provider, then this parameter isn't configurable.
I'm unable to reproduce this issue, I've tried multiple models, including the Llama 3.1 8b with the most recent version of Ollama.

How did you ensure that ChatGPT waits for the entire response before rendering it on the screen?

**Comment by scscgit** [comment]
It has an interesting behavior, I tried a prompt `write numbers from 1 to 1000` and it got stuck as usual, but after a couple of minutes around number 500 it suddenly wrote everything and started slowly continuing token by token (before getting stuck around 650). Though I'm unable to reproduce it - right now at the very moment when CodeGPT starts showing any output, Ollama gets unlocked, meaning my other client starts generating its new response after being blocked, so it's definitely not streaming. Are there any logs for the requests?

**Comment by AdemJensen** [comment]
I am getting the same issue here: Just install the plugin from the marketplace, and set backend to Ollama, chat and you see the bug.

**Comment by AdemJensen** [comment]
> I am getting the same issue here: Just install the plugin from the marketplace, and set backend to Ollama, chat and you see the bug.

And if you set Provider to "Custom OpenAI" and configure ollama URL & model manually, it will be fine, so it seems that this is an issue only for Provider "Ollama"

**Comment by carlrobertoh** [comment]
oke, I think I found the issue. Their `POST /api/chat` API streaming seems to be broken. I will change the underlying API to use the `/v1/chat/completions` endpoint instead.

**Comment by lingfish** [comment]
Hi @carlrobertoh ... This is not resolved for me, using version 2.11.7-241.1 in PyCharm 2024.2.1 (Professional Edition).

It is still using `/api/chat`
