### ISSUE TITLE
Unable to delete downloaded models in CodeGPT plugin on macOS

### ISSUE THREAD

**Issue by NoamHarel1** [carlrobertoh/CodeGPT#647]
Hi CodeGPT team,

I'm experiencing an issue with the CodeGPT plugin where I'm unable to 
delete a model that I've downloaded. The model is still listed as being 
installed, and I'm missing a button to remove it.

Specifically, when viewing the list of models in the plugin settings, I 
don't see any option or button to delete the model. I'd expect to see a 
"Remove" or "Delete" button next to each model, but it's not there.

**Expected Result:**

I expect to be able to safely remove the model from the plugin settings by 
clicking on a corresponding button.

**Actual Result:**

There is no button to delete the model. The only option is to try and 
uninstall the entire plugin, which would also remove any other models I've 
downloaded.

Please let me know if there's any additional information you need to help 
resolve this issue!

**Comment by carlrobertoh** [comment]
Hi, the downloaded models are located in your home directory: `.codegpt/models/gguf` 
Delete the corrupted model and then try again.
