### ISSUE TITLE
Cannot clear history of Chat 1

### ISSUE THREAD

**Issue by scscgit** [carlrobertoh/CodeGPT#651]
### What happened?

All chats other than Chat 1 have an X button to delete that chat history.

![image](https://github.com/user-attachments/assets/6f5a3739-d5d3-4159-b09a-7f2b516562b3)

However, sometimes a new "Clear Window" button appears when you have Chat 1 open (it didn't show immediately after restarting IDE):

![image](https://github.com/user-attachments/assets/406c07ac-19f6-4d05-9fc1-c3a4405f1b69)

I used it (though the icon made it very difficult to recognize), but after I restarted IDEA, the history of Chat 1 **returned back**.

A workaround is to delete individual messages one by one, but surely that's not how we're supposed to do it.

### Steps to reproduce

Write any messages to Chat 1.

### CodeGPT version

2.9.0-241.1

### Operating System

Windows

**Comment by carlrobertoh** [comment]
Thanks for reporting! This will be fixed in the next release.
