### ISSUE TITLE
Code Completions 

### ISSUE THREAD

**Issue by SnowWindDancing** [carlrobertoh/CodeGPT#662]
### What happened?

Code Completions custom fim no work.
![image](https://github.com/user-attachments/assets/213200c1-ea47-4b6d-a8bd-f73e1db8404f)

### CodeGPT version

2.9.0-241.1

### Operating System

Windows

**Comment by carlrobertoh** [comment]
First of all, it seems you have a typo in "$SUBFIX". Secondly, are you sure that `Qwen1.5-110B-Chat` supports code completions, or more specifically, DeepSeek Coder FIM template?

**Comment by SnowWindDancing** [comment]
we use qwen by vllm，it has OpenAI adaptation interface. After I corrected my word errors，this is request body
![image](https://github.com/user-attachments/assets/8edce86c-cd64-4ced-8c5a-d6169ccf38a3)
And  prompt only set  `$PREFIX`   worked,  but prompt set  `    $PREFIX` can not work.

**Comment by carlrobertoh** [comment]
Hmm, it seems that the placeholders aren't being replaced with the actual values. I'll take a look at it soon.
