### ISSUE TITLE
Every time I update the plug-in version, all of my Settings are gone

### ISSUE THREAD

**Issue by MangerLe** [carlrobertoh/CodeGPT#67]

**Comment by kalbert312** [comment]
I also have this issue. I needed to renter the API key on each update while on IntelliJ/Rider 2022.3.2. I'm using https://plugins.jetbrains.com/plugin/20868-settings-sync to sync my settings, not sure if it matters. Great plugin otherwise!

**Comment by MangerLe** [comment]
> I also have this issue. I needed to renter the API key on each update while on IntelliJ/Rider 2022.3.2. I'm using https://plugins.jetbrains.com/plugin/20868-settings-sync to sync my settings, not sure if it matters. Great plugin otherwise!

Previously, you did not lose your configuration with the new plug-in version

**Comment by carlrobertoh** [comment]
Hi!

Since the plugin is still in an early phase, I'm changing some of the settings regularly and creating a new state instances to prevent any deserialization errors happening.

Hopefully soon the plugin updates will be more stable.
Thank you!

**Comment by spyro2000** [comment]
Same for me, have to create a new API key each time.

**Comment by carlrobertoh** [comment]
Sorry to hear! I'm trying to keep the state changes at minimum.
