### ISSUE TITLE
Cannot parse response from ollama (open-webui) when response does not contain header Content-Type: application/x-ndjson

### ISSUE THREAD

**Issue by unixshaman** [carlrobertoh/CodeGPT#674]
### Describe the need of your request

It looks like the image below
![image](https://github.com/user-attachments/assets/67739d28-faa1-40c7-bcdf-08f7b1c83776)

This is due to the error described in the next issue.
I created an issue in the open-webui project to add the response header like in ollama: https://github.com/open-webui/open-webui/issues/4915.

### Proposed solution

Perhaps in this project it would also be nice to do some handling for when the header Content-Type is missing and try to recognize the message body if possible.

### Additional context

Using Ollama (Local) provider.

**Comment by carlrobertoh** [comment]
This issue should be fixed in the latest version (2.11.1). Please reopen the ticket if it is still reproducible.
