### ISSUE TITLE
ChatGPT response 

### ISSUE THREAD

**Issue by dongxinxing** [carlrobertoh/CodeGPT#683]
Hello, after I installed this plugin, I entered the question in the chatGPT interface, and the answer I got was in English, I want to get the answer that is Chinese by default, please should I set it in that place.

**Comment by dongxinxing** [comment]
你好，我安装好了这个插件之后，我在chatGPT界面输入问题，得到的回答是英文的，我想得到默认是中文的回答，请问我应该在那个地方设置。

**Comment by kytrun** [comment]
Add a custom posona in the setting, and choose it with double click. then you can see it at the top of the conversation window.
