### ISSUE TITLE
Personas can't be displayed or modified

### ISSUE THREAD

**Issue by CharlesFromBytel** [carlrobertoh/CodeGPT#686]
### What happened?

In the settings, the Personas can't be displayed, keep `Loading…`
The other settings are fine.

### Relevant log output or stack trace

```shell
Nothing in the log.
```

### Steps to reproduce

I don't know since when it happened. Initially, when I started using the plugin two weeks ago, I deleted all the personas (if I remember right) to only keep one. I was about to modify that one persona when I stumble upon the ever-loading screen.
Oddly, when I look in the chat window, my `Default` persona in the top part of the screen is still there. When I use the `@` to list the personas, they seem to be all there too.
![image](https://github.com/user-attachments/assets/7e7f8364-02b7-4b12-bf29-79038037f316)
![image](https://github.com/user-attachments/assets/5be6b445-17ac-4e20-88ef-ec37f7e38072)
![image](https://github.com/user-attachments/assets/365cd652-6c78-429c-ab8f-c84b8c270fbe)

### CodeGPT version

2.11.0-241.1

### Operating System

Windows

**Comment by carlrobertoh** [comment]
Thanks for reporting!

This seems like some sort of deserialization error where the modified record can no longer be recognized. As a workaround, you could try resetting the state by deleting the file `CodeGPT_PersonaSettings.xml` from the plugin's settings.

https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs
