### ISSUE TITLE
Explanation of changes in the commit

### ISSUE THREAD

**Issue by rakleed** [carlrobertoh/CodeGPT#688]
### Describe the need of your request

Sometimes there can be a lot of changes in a commit, and you would like to quickly understand what changes are being made. Or something is unclear, because you don’t know the specifics of the language, but you need to quickly understand what the author did. And then you have to try to figure it out yourself, which can be time-consuming.

### Proposed solution

Add an "Explain changes" option to the context menu when right-clicking on a commit in Git Log (the JetBrains AI plugin has similar functionality).

**Comment by carlrobertoh** [comment]
This seems a really cool idea!

Would something like this work?


https://github.com/user-attachments/assets/f8f48fca-17d2-48a8-ac2f-f0577d4837b4

**Comment by carlrobertoh** [comment]
Thanks for the link!

I will add this in the next release.
