### ISSUE TITLE
Focus on textarea when opening CodeGPT chat windows

### ISSUE THREAD

**Issue by CharlesFromBytel** [carlrobertoh/CodeGPT#691]
### Describe the need of your request

Just to stay keyboard friendly like the rest of the IntelliJ windows, it would be nice to be able to open the chat window and have the cursor already on the textarea by default. Today, it is on the persona selection, but even if we type Enter, it doesn't open the persona, so the cursor at that position by default isn't very useful.
Today, I pressed shift tab twice to get to the textarea.

**Comment by carlrobertoh** [comment]
Thanks for reporting! This issue will be fixed in the next version.
