### ISSUE TITLE
Anthropic doesn't have code completion with own api key

### ISSUE THREAD

**Issue by D214238** [carlrobertoh/CodeGPT#695]
### Describe the need of your request

A lot of other models where you provide your own api key have the option for code completion, but anthropic doesn't. I can't find anywhere why that's the case.

### Proposed solution

Add code completion option to anthropic when using own api key.

**Comment by carlrobertoh** [comment]
Code completion only works with models that are trained on FIM tokens. Unfortunately, Anthropic doesn't provide one, or at least not that I'm aware of.

Today, I'd recommend using `GPT-3.5 Turbo Instruct` for code completions and `Claude 3.5 Sonnet` for everything else. However, today, this can only be achieved via the CodeGPT API. In the future, I'll extract code completion to its own configuration form, enabling users to use separate providers for separate features.

**Comment by D214238** [comment]
Ah that makes sense. Didn't come to mind. Thanks for the quick and helpful response.
