### ISSUE TITLE
Edit Code popup not using Azure OpenAI

### ISSUE THREAD

**Issue by gmontamat** [carlrobertoh/CodeGPT#696]
### What happened?

I use CodeGPT with custom Azure OpenAI credentials to chat with a deployed gpt-4o model (PyCharm Community 2024.2.1)

When trying out the Edit Code popup feature, even though Azure OpenAI is selected as provider, I get: "The model 'gpt-4o' is not available under your current pricing plan."

### Steps to reproduce

- Select code
- Right click menu -> CodeGPT -> Edit Code
- Write edit prompt
- Hit Submit

Expected behavior: it uses Azure OpenAI gpt-4o model to prompt edit

### CodeGPT version

2.11.1-241.1

### Operating System

macOS

**Comment by kcupr** [comment]
https://github.com/carlrobertoh/CodeGPT/blob/37adb90587283a01cdccf4cb10a370c777e84f5b/src/main/kotlin/ee/carlrobert/codegpt/actions/editor/EditCodeSubmissionHandler.kt#L38

**Comment by gmontamat** [comment]
thanks!
