### ISSUE TITLE
The model: `gpt-4` does not exist

### ISSUE THREAD

**Issue by spyro2000** [carlrobertoh/CodeGPT#70]
Hi there,

loving this plugin, but it's still not possible to use GTP-4. It just says

`The model: `gpt-4` does not exist`

I have a GPT Plus subscription and it works in the normal web interface. What am I doing wrong here...?

**Comment by arcticlinux** [comment]
You have to have access to gpt-4 via the gpt-4 api waitlist
https://openai.com/waitlist/gpt-4-api
