### ISSUE TITLE
Add support for alternative GPT-4 versions

### ISSUE THREAD

**Issue by fantom0005** [carlrobertoh/CodeGPT#71]
We need to add support for alternative versions of GPT-4, such as gpt-4-0314, gpt-4-32k, and gpt-4-32k-0314. This will enable users to utilize different configurations according to their specific requirements. Please consider implementing the following:

1. Update the model loading process to handle alternative GPT-4 versions.
2. Update documentation to include instructions for using alternative GPT-4 versions.

This enhancement will broaden the use cases for our project and provide users with additional options.

**Comment by carlrobertoh** [comment]
`gpt-4-32k` model has been added in version 1.10.3. Will handle the other functionality in a separate ticket.
