### ISSUE TITLE
Edit code stops early on longer file

### ISSUE THREAD

**Issue by jurmous** [carlrobertoh/CodeGPT#717]
### What happened?

I picked a longer file, select all code and run a code edit with Claude Sonnet 3.5. It goes through quite a bit of the file and then stops, deleting the rest. I expect it to continue with the whole file (Apps like Cursor do rewrite the complete file)

### Steps to reproduce

Pick a longer file. Run code edit. See it quiting while not completing the file

### CodeGPT version

2.11.3-241.1

### Operating System

macOS

**Comment by carlrobertoh** [comment]
Hi. Try increasing the `maxTokens` property in the settings.

Settings > CodeGPT > Configuration > Max completion tokens
