### ISSUE TITLE
Add a custom prompt on the left side of the input box.

### ISSUE THREAD

**Issue by MiniFullC** [carlrobertoh/CodeGPT#72]
Very useful! Thank you to the author~ I have a suggestion: 
Add a custom prompt on the left side of the input box, as shown in the picture:

![image](https://user-images.githubusercontent.com/37063727/229363932-819a647c-107b-4ff0-81de-84861c051d6b.png)

You can look at [awesome-chatgpt-prompts](https://github.com/f/awesome-chatgpt-prompts) to find interesting features to import into the app.

It would be great to be able to import prompts from a custom CSV file, just like the **prompts.csv** file in this repository.

The suggestion is to use the forward slash shortcut key to conveniently use prompts.

**Comment by carlrobertoh** [comment]
Hi, thank you for the feature request!

This seems like a nice idea altho some of these prompts are rather useless when it comes to developer experience (e.g. "act as a rival chess player"). Also there are some plans replacing the Java Swing components (JTextArea and JButton) with browser based components and that might complicate few things. 

However, I'm planning on adding a support for overriding the request params and these system lvl prompts can be one of the things that user could override altho you don't get that nice user experience as shown in the picture.
