### ISSUE TITLE
Failed to connect to localhost/[0:0:0:0:0:0:0:1]:58148

### ISSUE THREAD

**Issue by linpan** [carlrobertoh/CodeGPT#724]
### What happened?

Failed to connect to localhost/[0:0:0:0:0:0:0:1]:58148

### CodeGPT version

lastest version

### Operating System

macOS

**Comment by carlrobertoh** [comment]
It appears that your remote server is offline, therefore CodeGPT is unable to establish a connection. Closing this issue as it's not related to the plugin itself.
