### ISSUE TITLE
how to edit large files?

### ISSUE THREAD

**Issue by AndreySocium** [carlrobertoh/CodeGPT#728]
### What happened?

I use a plugin for VS Code. My file is 672 lines. I write a prompt, but the page is cut off and at the bottom of chat I see this "...542 lines truncated". The responses from gpt also come cut off. How can I edit the entire document?
look at the screenshot pls. In preferences i can't change anything.
![codegpt](https://github.com/user-attachments/assets/b28ebd3e-6dc2-4248-8f62-584ec50a14e4)
<img width="1496" alt="Снимок экрана 2024-10-08 в 16 22 59" src="https://github.com/user-attachments/assets/d2ace8c0-4ace-4d31-bd63-792f39bda0bd">

### CodeGPT version

3.5.116

### Operating System

macOS

**Comment by carlrobertoh** [comment]
Hi, it looks like you're using the wrong version of CodeGPT. This issue board is for [JetBrains plugin](https://plugins.jetbrains.com/plugin/21056-codegpt).
