### ISSUE TITLE
Use Custom OpenAI Provider and set stream to false got "Unknown API response"

### ISSUE THREAD

**Issue by gameraroma** [carlrobertoh/CodeGPT#736]
### What happened?

Hi, I've set as this below
![image](https://github.com/user-attachments/assets/7a82c46c-b126-4d8b-b72e-d846ed88dfa3)

but I've got this error
![image](https://github.com/user-attachments/assets/e44d5dc8-88bf-4b7a-b039-5020059664ea)

It should be compatible with this schema as example json below,

`{
  "id": "cmpl-q3z01d5bueffqs7nmnpum",
  "object": "text_completion",
  "created": 1728997876,
  "model": "meta-llama/Llama-3.2-3B-Instruct/Llama-3.2-3B-Instruct-Q8_0.gguf",
  "choices": [
    {
      "index": 0,
      "text": "",
      "logprobs": null,
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 150,
    "completion_tokens": 0,
    "total_tokens": 150
  }
}`

### CodeGPT version

2.11.5-241.1

### Operating System

macOS

**Comment by linpan** [comment]
yes, use ollama okay .

**Comment by carlrobertoh** [comment]
Unfortunately, code completion does not work with non-streaming requests (yet).
