### ISSUE TITLE
Edit Code action returns `NULL`

### ISSUE THREAD

**Issue by davidgilbertson** [carlrobertoh/CodeGPT#737]
### What happened?

I select a function, and perform the "Edit code" option and type "Make this code better".

It just puts `NULL` where the code was.

![image](https://github.com/user-attachments/assets/d5abf1bb-9432-4d5d-adb9-985f3a4fe522)

If I use the chat instead it works, using the same model, so I know it's picking up my API key correctly.
![image](https://github.com/user-attachments/assets/a49c9949-b503-4b5d-b810-87ea988e7d23)

I believe my settings are correct:
![image](https://github.com/user-attachments/assets/9a450360-c0f2-4f6f-a0f1-4250994f6b8c)

All the OpenAI > GPT-* models do the same thing, insert `NULL` where the code was. The `o1-preview` model raises an error, which I think was reported elsewhere.

If I change the model to **GPT-4o-mini - FREE** it works (although it puts the changed code BEHIND the popup, so now I need to grab the mouse to move it to see if I want to accept it or not).
![image](https://github.com/user-attachments/assets/52894220-b4dd-4af9-b79c-81ed59e38be1)

### Relevant log output or stack trace

```shell
2024-10-16 10:32:04,311 [ 839614]   INFO - STDERR - [OkHttp https://api.openai.com/...] INFO ee.carlrobert.llm.completion.CompletionEventSourceListener - Request opened.
2024-10-16 10:32:04,312 [ 839615]   INFO - STDERR - [OkHttp https://api.openai.com/...] INFO ee.carlrobert.llm.completion.CompletionEventSourceListener - Request closed.
2024-10-16 10:32:07,876 [ 843179]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.SdkEntity to files
2024-10-16 10:32:07,877 [ 843180]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.LibraryEntity to files
```

### Steps to reproduce

Not sure, I just just installed the extension, tried it, and it gave this error.
I tried it in another project and got the same error.
Note that the `Request closed` is firing about 1 ms after the `Request opened`, is that a clue?

### CodeGPT version

2.11.6-241.1

### Operating System

Windows

**Comment by davidgilbertson** [comment]
I just tested with llama3.2 running locally via Ollama and that works, although it puts a full markdown codeblock in my code, with the backticks.
![image](https://github.com/user-attachments/assets/887db97d-be24-4138-82c2-b3ea9a372099)

And it works with Claude too:
![image](https://github.com/user-attachments/assets/7f425fe6-6b25-4fbf-99ae-3380d0c89c5e)


So the issue is somewhere at the intersection of
 - the "Edit code" feature (not chat)
 - OpenAI API with my own API key (not the CodeGPT models)

**Comment by carlrobertoh** [comment]
Thank you for reporting! I will have a look at it soon.

**Comment by davidgilbertson** [comment]
You work fast, nice!
