### ISSUE TITLE
1.9.0: "You exceeded your current quota"

### ISSUE THREAD

**Issue by spyro2000** [carlrobertoh/CodeGPT#74]
<p>You exceeded your current quota, please check your plan and billing details.</p>

I have a ChatGPT plus plan and can use the service as normal by their website (currently only using GPT-3.5 because GPT-4 seems not work via plugin).

What can I do here? Thank you!

**Comment by spyro2000** [comment]
Hi @carlrobertoh,

thanks for your response. It looks like this:

![image](https://user-images.githubusercontent.com/8479925/229852527-066f01a4-0ac8-4f44-b826-f3d1a44aa814.png)

It's a little bit strange, here's my paid plan for ChatGPT:

![image](https://user-images.githubusercontent.com/8479925/229852829-8ea9fdf6-090a-4b5a-8d9d-e34ec200f0af.png)

On https://chat.openai.com/ it looks like this:

![image](https://user-images.githubusercontent.com/8479925/229853123-81c0fa46-a1ec-4f7b-8df7-a87c54e18631.png)

**Comment by carlrobertoh** [comment]
`ChatGPT Plus` and `ChatGPT/OpenAI API` are 2 different things - the Plus subscription charges you 20$ per month for unlimited use of browser based ChatGPT while the API has a pay-per-use pricing model, which charges you based on the used tokens.

I'd suggest either buying a certain amount of tokens or creating a new account which should give you limited amount of free tokens for 3-months period.

**Comment by spyro2000** [comment]
Hmm, thank you. Looks like someone needs to develop some tech to scrape this info directly from the web UI... ;) It's too risky for me to now having a flat rate model available, not your fault, of course. As I got this, even if I buy tokens etc. GPT-4 will still not work if OpenAI didn't add each individual user to their waiting list.

To be serious, I will continue to copy&paste the code in the browser window then, seems like this the only way ATM for me.

Thank you anyway.

**Comment by olosegres** [comment]
I have just registered openai account, did not pay for anything and did not add cards.
I've added api key to plugin, but I always get message "You exceeded your current quota, please check your plan and billing details."

And one more thing - using version 1.9.1 it is not displayed in the chat, only in MD log. Using version 1.7.1 this message is displayed in plugin chat.

**Comment by carlrobertoh** [comment]
@olosegres Thank you for reporting.

Are you able to hit the API directly?
```
curl https://api.openai.com/v1/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -d '{
  "model": "text-davinci-003",
  "prompt": "Say hello in 3 different languages.",
  "temperature": 0.9,
  "max_tokens": 150,
  "top_p": 1,
  "frequency_penalty": 0,
  "presence_penalty": 0.6
}'
```

**Comment by olosegres** [comment]
@carlrobertoh 
I got the same error
`{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}`

It seems like 
> new account which should give you limited amount of free tokens for 3-months period

Is not an option anymore
