### ISSUE TITLE
LM Studio support is flaky and needs work

### ISSUE THREAD

**Issue by Morriz** [carlrobertoh/CodeGPT#741]
### Describe the need of your request

Hi, thanks for the project first of all. I use LM Studio extensively and have no need for other solutions that unnecessarily copy gigabytes of models that I already have.

Now, I notice the following:
- LM Studio is a connection option for chat, but does not query the running models for us to choose?
- LM Studio is not a connection option for autocomplete?

### Proposed solution

LM Studio fully supported, also for autocomplete.

**Comment by xardbaiz** [comment]
Hello, @Morriz 
If it's still relevant I described how to get more from CodeGPT and local LM Studio here:
https://github.com/carlrobertoh/CodeGPT/issues/384#issuecomment-2473137768

**Comment by Morriz** [comment]
@xardbaiz  Your solution is not available to me in the plugin. No such feature "Provider" with option "Custom OpenAI" exists in my UI. Where can we see that?

**Comment by xardbaiz** [comment]
@Morriz yes. Autocompletion FIM teplate you choosing depending on the model in use

### Just as example
If you load QwenCode to LM Studio then choose "Qwen" from fixed dropdown list

#### CodeGPT
![image](https://github.com/user-attachments/assets/334c0751-733e-4c4d-be0a-7486209acac3)

#### LM Studio
![image](https://github.com/user-attachments/assets/b419ec01-3f5e-4851-875d-cdc3714c5974)

**Comment by Morriz** [comment]
Are we talking about vscode here? I am seeing screenshots of some web application. Can you provide vscode walkthrough video/screenshots describing how to get autocomplete working?

**Comment by carlrobertoh** [comment]
@Morriz Are you sure you're using the correct extension?

https://plugins.jetbrains.com/plugin/21056-codegpt

**Comment by Morriz** [comment]
Yes, when I open it, it shows a black sidebar, I just can't get the autocompletion to work.

You show a full page something, not the sidebar...and you keep showing screens that I can't get to.

**Comment by Morriz** [comment]
there is only one CodeGPT in vscode...now I see your plugin is for jetbrains? What a waste of time
