### ISSUE TITLE
Streaming responses for ollama aren't working

### ISSUE THREAD

**Issue by lingfish** [carlrobertoh/CodeGPT#744]
This is not resolved for me, using version 2.11.7-241.1 in PyCharm 2024.2.1 (Professional Edition).

ollama version is 0.3.13

It is still using `/api/chat`

Adding more to this, `/api/chat` streams just fine by default, tested with:

```bash
curl http://localhost:11434/api/chat -d '{
  "model": "llama3.1",
  "messages": [
    {
      "role": "user",
      "content": "why is the sky blue?"
    }
  ]
}'
```

_Originally posted by @lingfish in https://github.com/carlrobertoh/CodeGPT/issues/646#issuecomment-2423597539_

**Comment by carlrobertoh** [comment]
Thanks for reporting! This issue will be fixed in the next release.
