### ISSUE TITLE
Code completion Chinese preview garbled

### ISSUE THREAD

**Issue by qingyanbaby** [carlrobertoh/CodeGPT#754]
### What happened?

![image](https://github.com/user-attachments/assets/49806990-3f55-4e9a-b7af-3a5759e8185e)
Code completion preview shows Chinese characters as garbled text, but the completed code displays correctly after selection. The issue only occurs during the preview stage.

### CodeGPT version

2.12.1

### Operating System

Windows

**Comment by LinWanCen** [comment]
请教大佬如何解决ProxyAI代码补全的中文问题的？

**Comment by qingyanbaby** [comment]
> 请教大佬如何解决ProxyAI代码补全的中文问题的？

把第一字体换成中文字体
