### ISSUE TITLE
Allow to delete default personas

### ISSUE THREAD

**Issue by jseparovic1** [carlrobertoh/CodeGPT#755]
### Describe the need of your request

There are way too many default personas. In users just use couple of them. When trying to use one of the personas with @persona it is really slow and hard to find specific one. 

### Proposed solution

Allow to delete default personas.

### Additional
<img width="827" alt="Screenshot 2024-11-05 at 12 03 22" src="https://github.com/user-attachments/assets/8a15e90a-e7db-4693-b0ef-7d177e1e9a99">
 context

**Comment by carlrobertoh** [comment]
Closing this. The default personas were removed a few versions back, in addition to other prompt configuration improvements.
