### ISSUE TITLE
Random personas and models in new chat in PyCharm

### ISSUE THREAD

**Issue by js-olx** [carlrobertoh/CodeGPT#762]
### What happened?

I am experiencing a very weird problem in Pycharm
when restarting the IDE, every time I have a bit of a random setting when it comes to persona or a provider
I would like to use only Custom: OpenAI version
yet sometimes I see that I am switche to OpenAI, sometimes to a concrete model (which I am suprised works without API key, as I am using API key only for the custom model with OpenAI like interface)

### Steps to reproduce

1) set in settings a default provider to be Custom: OpenAI
2) restart Pycharm
3) open chat and find different provider selected

### CodeGPT version

2.12.3-241.1
on
PyCharm PyCharm 2024.3 (Professional Edition)
Build #PY-243.21565.199, built on November 13, 2024

### Operating System

macOS

**Comment by carlrobertoh** [comment]
Thanks for reporting this! I have also noticed some weird behaviours related to Personas in general, and I will fix these in the next major release.
I will probably also get rid of the hundreds of predefined Personas and consolidate all prompts into a single configuration table.

**Comment by xentanium** [comment]
Just to add... I really love this plugin and appreciate having it available... but I'm having the same issue regarding model selection in IntelliJ IDEA. In particular, when I attempt to change the model to 'Custom: OpenAI' from the dropdown in the Chat tab the behaviour is to spawn a new chat tab in the CodeGPT window. This new chat has a random model even though I selected 'Custom: OpenAI' from the dropdown from the original chat window. If I go back to the original chat tab the model has not changed from whatever random model was showing previously.

It's often impossible to set the model to 'Custom: OpenAI'.

**Comment by carlrobertoh** [comment]
Issues around the Custom OpenAI model change should be fixed in the latest version (2.14.3). Please reopen the ticket if the issue still persists.
