### ISSUE TITLE
sometimes the response is cut off and the full response is not displayed

### ISSUE THREAD

**Issue by LightToDo** [carlrobertoh/CodeGPT#768]
### What happened?

Hello, I use Jetbrain IDEA. Here's a bug. When using the custom OpenAI provider(Mistral AI), the model's response gets cut off after I give it a prompt to chat. However, when I close the current chat tab and reopen it from the chat history, the previously cut-off response is shown in full. This issue occurs frequently when using the Google Gemini provider.

### Steps to reproduce

1. Open a chat tab, chat 1.
2. Type in any prompt.
3. Send the prompt.
4. Wait for the response to populate.
5. Once the response is complete, review the response, but sometimes the response is cut off and the full response is not displayed.
6. Open a new chat tab, chat 2.
7. Close the other chat tab, the chat 1.
8. Open chat history, select the conversation for the chat 1.
9. Chat 2 tab, that is the chat 1, appears, review the response, the full response is now visible.

### CodeGPT version

2.12.4-241.1

### Operating System

Windows

**Comment by carlrobertoh** [comment]
Seems to be related to #757. This will be fixed in the next release.
