### ISSUE TITLE
option to resize input field

### ISSUE THREAD

**Issue by BenoitDeo** [carlrobertoh/CodeGPT#77]
Will it be possible to have an option to resize the input field? thanks!

**Comment by carlrobertoh** [comment]
Hi! 

It is possible, however I'm not sure when I'll find a time to do it.
I'm also planning to replace the `JBTextArea` with a browser based component which imo gives more flexibility to customize the field and its functionality.

**Comment by AustinColby** [comment]
If it's too much trouble to make it resizable, in the meantime could we just have textarea row count set to something more reasonable (e.g. 6 rows instead of the current 2).

**Comment by carlrobertoh** [comment]
@AustinColby I will try to prioritize this feature. Most likely, a row count of 6 is going to look ugly on smaller screens.

**Comment by carlrobertoh** [comment]
Closing this issue.
The height of the text area will grow according to the content (v2.0.0).
