### ISSUE TITLE
Open a new chat on each action is missing

### ISSUE THREAD

**Issue by Yanichar** [carlrobertoh/CodeGPT#778]
### Describe the need of your request

The 'Open a new chat on each action' option has disappeared in the latest version of the plugin, but I believe this is a very useful feature to avoid cluttering the ai context. Is this a bug, or do you no longer plan to bring it back?

**Comment by carlrobertoh** [comment]
Hi. This setting has been relocated and can now be found in Prompts settings under the Chat Actions section.
<img width="971" alt="Screenshot 2024-12-01 at 11 04 05" src="https://github.com/user-attachments/assets/85ce82ed-e45b-4155-9788-13dc97001eab">
