### ISSUE TITLE
CodeGPT stuck on responding

### ISSUE THREAD

**Issue by mochitoo35** [carlrobertoh/CodeGPT#779]
### What happened?

I am running local model ollama qwen-2.5 coder 7b which runs fine on everything else such as Continue and open-webui but when I try to send a message to codegpt on vscode extension it is permanently responding.
![image](https://github.com/user-attachments/assets/30b05575-d144-429c-b76f-31c9689efbd5)

### CodeGPT version

3.2.7

### Operating System

Windows

**Comment by carlrobertoh** [comment]
Hi, this GitHub repository is for the [JetBrains extension](https://plugins.jetbrains.com/plugin/21056-codegpt), which has no affiliation with https://codegpt.co/.

Please contact them via other channel.
