### ISSUE TITLE
this is a bug

### ISSUE THREAD

**Issue by fatebugs** [carlrobertoh/CodeGPT#78]
After I add a new dialogue, I can’t choose it in the old chat
Please take the time to take a look
Many thanks！！！！！！！！

![iShot_2023-04-09_11 14 50](https://user-images.githubusercontent.com/65278566/230752269-4a8dc53c-4414-4fca-89e6-451d2a99555d.gif)

**Comment by carlrobertoh** [comment]
Hi, this bug is fixed in version 1.10.0
