### ISSUE TITLE
Easier way needed to modify and resend a request

### ISSUE THREAD

**Issue by ferenci84** [carlrobertoh/CodeGPT#791]
### Describe the need of your request

In the chat window, if you send a prompt and it goes wrong, there is no easy way to edit the prompt and resend it. You can delete all together with the AI response, but if you didn't save the markdown format before, you have to reformat the whole message again.

### Proposed solution

Either one of the above would resolve the issue:
Solution 1: A button to copy the user message in markdown format
Solution 2: Edit option: this would open a text editor in place of the message. This would be useful for other purposes; for example, you may add additional context in previous messages, or you would be able to edit the AI responses so that it can be used as a context for subsequent messages.

It would be ideal to have both.

### Additional context

My current workflows:

Workflow 1 (if I know that I will need more than 1 attempt):

- Write the message in a markdown scratch file
- Copy & paste and send
- Evaluate the response

If it goes wrong:
- Delete the last response; this deletes the last user message too
- Edit the markdown
- Copy & paste and resend
- Evaluate again

Workflow 2 (if I forgot to save):

- Write the message in the chat window as usual and send
- Evaluate the response

If it goes wrong:
- Copy the formatted message
- swear and reformat again back into markdown
- resend

Solution 1 AND/OR Solution 2 would make both workflows easier.

**Comment by carlrobertoh** [comment]
Thank you for the feedback!

Adding support for editing recent input is definitely nice thing to have, but unfortunately, I am not considering it a high priority.

As a workaround, I suggest opening the entire conversation in another tab, which allows you to copy your recent inputs in markdown format:

<img width="240" alt="conversation_in_md" src="https://github.com/user-attachments/assets/2aceb451-aff8-468e-b85b-b980009b6cdf" />

Even though I've excluded this from my own roadmap, I'm still open to PRs to make this thing possible :)

**Comment by ferenci84** [comment]
I am willing to contribute. Are you willing to talk about what an optimal implementation would look like?

**Comment by carlrobertoh** [comment]
I believe the most optimal solution would be adding a Copy icon button in the user message panel header, which will simply copy the user message to the clipboard.

Another option would be the actual editing of the user message. However, this requires more work since there are many use cases that need to be considered, as the message can contain several code blocks mixed with regular text, images, etc.

**Comment by carlrobertoh** [comment]
@ferenci84 actually, can you hold off on this implementation? I'll handle it myself, since I want to arrange a few other icons around.
