### ISSUE TITLE
Keyboad shortcut or @action to add all open files to context

### ISSUE THREAD

**Issue by evrenesat** [carlrobertoh/CodeGPT#796]
### Describe the need of your request

When I work on implementation of a feature/function, most of the time all relevant files end up being open. Currently I switch to Project > Open files toolbar and select all files with mouse, then I can add them to context in one go. This hugely improves the quality of the output. But having to switch to mouse is not fun.  Cmd+A includes parent folders so that's not helpful.  

### Proposed solution

Any of the following would be enough to enable a keyboard only flow:
- An IDE action to work live cmd+A but selects only files in the "Open files" window.
- A global action to add all open files to CodeGPT context.
- An `@Open files` chat command to include all open files to chat.

**Comment by carlrobertoh** [comment]
Thanks for reporting!

Currently, when you include files using the '@' command, the list of files are sorted with open files appearing first, followed by the others. However, this doesn't solve the issue of including all open files in your session. I will most likely add a new sub-action under 'Files' as 'Include all open files', with an option to attach a shortcut for it.

**Comment by evrenesat** [comment]
Thanks, I'm looking forward to landing of that feature.
