### ISSUE TITLE
OpenAI Providers Not Working

### ISSUE THREAD

**Issue by rhonyabdullah** [carlrobertoh/CodeGPT#798]
### What happened?

Something wrong while using `OpenAI` providers, i already sets the token (subscribed as a ChatGPT+). Looking on OpenAi limit section i see there is no `GPT-4o` model so i switched to `GPT-4o-mini` but it tells i already exceed current quota.

### Relevant log output or stack trace

```shell
- Project `project id` does not have access to model `gpt-4o`
- Quota exceeded
```

### Steps to reproduce

![Screen Shot 2024-12-17 at 13 08 41 PM](https://github.com/user-attachments/assets/8ba3bd93-b338-4c6c-ba19-6bfecf66b742)

  Then i go to my `OpenAI` dashboard and enable the model trying my luck
![Screen Shot 2024-12-17 at 13 11 53 PM](https://github.com/user-attachments/assets/392a3fbc-4818-4002-8056-9203e3ada7c4)

![Screen Shot 2024-12-17 at 13 09 39 PM](https://github.com/user-attachments/assets/24066da2-c941-432e-9d94-c1ee2bd2dc5b)

### CodeGPT version

2.14.2-241.1

### Operating System

macOS

**Comment by carlrobertoh** [comment]
The error comes from OpenAI itself.

ChatGPT Plus and the OpenAI API are two different services - the Plus subscription charges you $20 per month for unlimited use of browser-based ChatGPT, while the API has a pay-per-use pricing model that charges you based on token usage.

OpenAI credit can be added from the following link: https://platform.openai.com/settings/organization/billing/overview
