### ISSUE TITLE
UI improvement - scrollbar style in dark mode

### ISSUE THREAD

**Issue by sintezcs** [carlrobertoh/CodeGPT#80]
Is it possible to remove the white scrollbar background when using a dark UI theme?

![Image copy](https://user-images.githubusercontent.com/2989480/230896019-5f88cd53-302e-45c5-b6bf-f54ce5034bbf.jpg)

**Comment by carlrobertoh** [comment]
Hmm, strangely it doesn't happen to me.

<img width="628" alt="Screen Shot 2023-04-10 at 13 15 32" src="https://user-images.githubusercontent.com/15891408/230900102-1fd8fd35-c367-435e-925b-5bfa7929bd93.png">

**Comment by sintezcs** [comment]
I've just found a way for you to reproduce it. I have this option enabled in MacOS:

<img width="767" alt="Screenshot 2023-04-13 at 13 55 21" src="https://user-images.githubusercontent.com/2989480/231737948-2007b127-d6c8-42f7-88b1-c8b8db71f47d.png">

**Comment by carlrobertoh** [comment]
Thank you! I'll see what I can do.

**Comment by carlrobertoh** [comment]
I couldn't find any good way to fix this, somehow the dark scheme isn't being applied to the browser.
The custom style looks okish but it still lacks styles when hovering over the scrollbar or when the content is being scrolled.

<img width="489" alt="Screen Shot 2023-04-14 at 12 18 33" src="https://user-images.githubusercontent.com/15891408/232030826-76523ae5-31ab-4d18-b1c7-b4a78e7db689.png">
