### ISSUE TITLE
strange replace in System.IO.Directory.GetFiles(@"\\.\pipe\")

### ISSUE THREAD

**Issue by rowi123** [carlrobertoh/CodeGPT#800]
### What happened?

when i paste System.IO.Directory.GetFiles(@"\\.\pipe\") i see System.IO.Directory.GetFiles(@"\.\pipe")
also when the AI talks i get the wrong string back

### CodeGPT version

2.14.2

### Operating System

Windows

**Comment by carlrobertoh** [comment]
Thanks for reporting! 

This will be fixed in the next release - https://github.com/carlrobertoh/CodeGPT/blob/master/CHANGELOG.md?plain=1#L16
