### ISSUE TITLE
"An error has occurred."

### ISSUE THREAD

**Issue by sgjohnson1981** [carlrobertoh/CodeGPT#801]
### What happened?

Suddenly received output like this: "An error has occurred. Please reach out to CodeGPT support for assistance." That's all it said.

### Relevant log output or stack trace

```shell
Please someone explain how to find the log output. I searched everywhere in /home/user/ but didn't find any log files relevant to CodeGPT. Not sure how to run a task with --stacktrace either.
```

### Steps to reproduce

I wasn't doing anything special. I was "referencing" a single file in the context. Token count was 4787 for the chat.

### CodeGPT version

2.14.2

### Operating System

Linux

**Comment by carlrobertoh** [comment]
Hi

Which model are you using? We're experiencing some technical issues with Llama 3.1 (405B) and Qwen 2.5 Coder due to the Fireworks API being down.

**Comment by sgjohnson1981** [comment]
Ah, ok. I'm using Qwen 2.5 Coder.

**Comment by sgjohnson1981** [comment]
Still curious though how to find the log and do --stacktrace.

**Comment by carlrobertoh** [comment]
The IDE logs, including errors from the plugin itself, can be found in the Help menu on the top bar via Help | Show Log in Finder. More information [here](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files).

However, the error you received — "An error has occurred. Please reach out to CodeGPT support for assistance.", is a generic CodeGPT API error and is not publicly accessible.

Closing this issue. The Qwen 2.5 Coder and Llama 3.1 (405B) are back to normal again.
