### ISSUE TITLE
click open in editor suggestion

### ISSUE THREAD

**Issue by fatebugs** [carlrobertoh/CodeGPT#84]
I hope that the codeGPT window will not be closed when opening markdown, so that I can continue to ask questions more quickly
Or there is such an option to choose whether to close
thanks

**Comment by fatebugs** [comment]
![image](https://user-images.githubusercontent.com/65278566/231974286-1d6f9d72-32ec-48ce-9b37-178302612808.png)

**Comment by carlrobertoh** [comment]
Hey, I closed the toolwindow on purpose since the MD file will be open in split editor and doesn't leave much space.
FYI: The opened file will not get updated while chatting if that's what you're expecting.
