### ISSUE TITLE
Suggestion: Add option to change displayed name in chat window

### ISSUE THREAD

**Issue by Adrian-at-CrimsonAuzre** [carlrobertoh/CodeGPT#89]
Since we can't seem to get an organization account, I have several keys under my account for our devs to simplify billing. As amusing as it is to have my name show up for everyone, it would be nice if this were configurable or pulled the name off your JetBrains account instead:
<img width="299" alt="image" src="https://user-images.githubusercontent.com/1719461/233719264-13086b02-df66-4863-8753-b01960da9505.png">

**Comment by carlrobertoh** [comment]
Hi, thank you for reporting!
I'll make the name configurable in the next release.

**Comment by carlrobertoh** [comment]
Display name has been made configurable with an option to disable fetching the OpenAI account name.
<img width="569" alt="Screenshot 2023-04-22 at 10 49 46" src="https://user-images.githubusercontent.com/15891408/233776840-ebdc80fc-f2cb-43b5-8335-908cf45805d8.png">

https://github.com/carlrobertoh/CodeGPT/releases/tag/1.10.4
