### ISSUE TITLE
How to install codegpt plugin from disk in pycharm

### ISSUE THREAD

**Issue by nimi73** [carlrobertoh/CodeGPT#91]
We are not able to add this github zip code as a plugin in Pycharm by using option as "Install plugin from disk". 
Because we need to change the temperature parameter.

Is there any way to get the chat history via api?

![Screenshot (2)](https://user-images.githubusercontent.com/99484051/234314881-a039b08b-9f10-408c-ab13-cf0eb2bbaf0e.png)

**Comment by nimi73** [comment]
Firstly thank you for your quick reply. Let me explain you in detail what we what to achieve.  we want to install our own version of the plug-in from the disk. The reason why we want to do that, 1) we want to change the temperature, 2) We want to save the API call data to track usage pattern and to see what calls people are making. Now the problem we are facing: 1) we are unable to install the plug-in from the disk. You can see the error in the screenshot.

**Comment by carlrobertoh** [comment]
It seems like the plugin wasn't built correctly because the error indicates that the `META-INF/plugin.xml` is missing or is invalid. To build the plugin, you need to run `./gradlew buildPlugin` command in the root directory.

**Comment by nimi73** [comment]
hey we tried the ./gradlew buildPlugin command but we are getting this error.

 
![c9f1056b-9598-43bc-be66-f275b91c08f3](https://user-images.githubusercontent.com/99484051/236404977-5cd8d6c2-f7d0-4445-9ffa-6c0c17cc20a3.JPG)

**Comment by carlrobertoh** [comment]
There seems to be problem with your JRE's truststore.

Assuming you're on Ubuntu, try to run this cmd:
```shell
update-ca-certificates -f
```

**Comment by nimi73** [comment]
Hi carlrobertoh,

I tried on windows OS and the build was successful, still the same error. Please find the screenshot for the same. Is there we are missing something while building the plugin? Also can you provide the steps to create plugin for CodeGpt and how to install the plugin in pycharm?

![build](https://github.com/carlrobertoh/CodeGPT/assets/99484051/f3b9419b-525e-4be2-a638-6359c9377b7a)
![build-1](https://github.com/carlrobertoh/CodeGPT/assets/99484051/143a1370-c329-4bde-aa09-1dfa6c6fc4e1)

**Comment by carlrobertoh** [comment]
It seems like you're compressing the build folder manually? The actual installation file is located inside `build/distributions` path.
