### ISSUE TITLE
code formatting when the response is cut off

### ISSUE THREAD

**Issue by louisice** [carlrobertoh/CodeGPT#92]
First of all, thank you very much for your plugin. It's really convenient to use in the IDE. 

I found a minor issue when using it to generate code. When the returned code is too long and needs to be cut off, the formatting may become incorrect when I proceed generating. 
After checking the Markdown format, I found that the previous message did not have the ending symbol of the code block.

![image](https://user-images.githubusercontent.com/29276312/234485855-c95b1d1a-08db-457e-a345-bbc172687807.png)
as shown, there are tow ``` symbols missing at the red arrows.  I understand that this is the content directly returned by ChatGPT, but is there a way for us to handle it?

Again, Thanks for your time.

**Comment by carlrobertoh** [comment]
Hi, I think the system prompt needs to be updated to be more precise.
https://github.com/carlrobertoh/CodeGPT/blob/master/src/main/java/ee/carlrobert/codegpt/client/CompletionRequestProvider.java#L49

**Comment by louisice** [comment]
> Hi, I think the system prompt needs to be updated to be more precise. https://github.com/carlrobertoh/CodeGPT/blob/master/src/main/java/ee/carlrobert/codegpt/client/CompletionRequestProvider.java#L49

I see, I never notice that before, even offcial site has this problem too.
![image](https://user-images.githubusercontent.com/29276312/235107312-06b02451-2382-4c53-ad7b-3b73cde3b5a9.png)

and I've tried several times to make it return 3 code block symbols first after I said go on. but it won't work.

**Comment by carlrobertoh** [comment]
Yeah... I think tweaking the system prompt might fix that.
