### ISSUE TITLE
Add Azure OpenAI Service support

### ISSUE THREAD

**Issue by renjfk** [carlrobertoh/CodeGPT#93]
I think it would be beneficial to add Azure OpenAI Service support since it might be possible for some companies to have AI tools usage policies which doesn't include direct OpenAI API usage. I can contribute to have this feature.

**Comment by shalak** [comment]
Here's my proposal on integrating the new feature of openai-client:1.0.10

This is the very first time I'm implementing any IntelliJ plugin, so any feedback will be appreciated :)
