### ISSUE TITLE
Android studio - markdown is not formatted

### ISSUE THREAD

**Issue by VitKap** [carlrobertoh/CodeGPT#94]
Hello,
GPT markdown text is not properly formated in Android Studio 2022.2 running on Ubuntu 20.04.

![Snímek obrazovky pořízený 2023-04-26 13-17-07](https://user-images.githubusercontent.com/52568038/234560604-1762af89-b691-48c1-982a-36cb86bc25e5.png)

Do someone know why / has someone the same problem?

**Comment by carlrobertoh** [comment]
Hi, are you using the latest version of the plugin? If not, then it seems like the `JBCefApp` is not supported in your IDE runtime.

**Comment by VitKap** [comment]
Yes I am using the newest version (1.10.4).  It is possible but I don't know why is not supported. I use the default boot Java runtime.

**Comment by VitKap** [comment]
Ok, so I found a solution. Android Studio runtime is not bundled with JCEF by default. Just follow steps from [this](https://issuetracker.google.com/issues/159933628#comment19) comment posted in issue tracker (tested in Android Studio Flamingo. For me the runtime [jbrsdk_jcef-17.0.6-linux-x64-b829.9.tar.gz](https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk_jcef-17.0.6-linux-x64-b829.9.tar.gz) works great.

https://issuetracker.google.com/issues/159933628#comment19

**Comment by carlrobertoh** [comment]
I'm glad you got it fixed on your own. 
Thank you for providing the details!
