### ISSUE TITLE
Plugin actions in currently opened chat context

### ISSUE THREAD

**Issue by shalak** [carlrobertoh/CodeGPT#97]
As of today, every time we send a snippet to CodeGPT it starts a new chat. It would be really beneficial if we're able to send it to currently opened one.

**Comment by vladimir-hodaryonok-idf** [comment]
yes, it's very bad expirience, when chatGPT do not know about previous messages in chat =(

**Comment by carlrobertoh** [comment]
Fixed in v2.0.0.
