### ISSUE TITLE
UX issue: Stop generating vs. Regenerate response

### ISSUE THREAD

**Issue by BenceSzalai** [carlrobertoh/CodeGPT#99]
Hi! Great plugin, I'm very happy with it.

However, there's this thing that I time-to-time accidentally hit [Regenerate response] when I am really trying to click [Stop generating].

Let's say ChatGPT generates a response. I can see the thing I am looking for early in the response. I don't want all the explanations, that usually comes after. I think to myself, well, generation costs money, energy and time, so let's just hit [Stop generating]. What happens instead that the very moment before I try to click [Stop generating], the generation finishes, so I hit [Regenerate response] instead. This is very bad as I loose the perfectly good text I already had, also I need to wait for generation again consuming more resources.

Imho the best would be to align the [Stop generating] button to the left and the [Regenerate response] button to the right. This way accidental clicks could be minimised.

On a side-note I think it would be reasonable also to keep the last response locally on [Regenerate response]. I understand why the chatGPT web UI gets rid of the last generated response when we ask for a Regeneration, but in a plugin, where our machine has full control, it sometimes could be beneficial to keep the generated text we have already received, after all we have paid for that already, and maybe it has merits, or maybe we are just curious if another generation could turn out better without loosing the generation we already acquired. The generated text we keep this way should indeed be excluded from what the AI is aware of, but it could be kept on the screen, maybe a bit greyed out or in italics or something, to indicate it is a local history only.

Thank you for considering this! I hope you like these ideas!

**Comment by carlrobertoh** [comment]
Hi @BenceSzalai, thank you for these ideas!

> I think to myself, well, generation costs money, energy and time, so let's just hit [Stop generating].

I'm not 100% sure, but I think stopping the generation has no effect on the usage. The usage is calculated based on the full prompt (previous messages + current prompt) that is being sent to the API.

> Imho the best would be to align the [Stop generating] button to the left and the [Regenerate response] button to the right. This way accidental clicks could be minimised.

Even tho it could minimise the accidental clicks, I don't think it would look that good on the window (or maybe it do 🤷‍♂️ ) - one of the buttons will be always disabled during the response generation.

I like the idea of keeping the previous generated response always on the window e.g. with an option to remove it. This was actually how it was done initially. Furthermore, we could add an option for user to decide which re-generated response to include in the ongoing conversation (e.g. adding a simple checkbox/radio button). This way the previous response will be always visible even on accidental misclicks.

**Comment by BenceSzalai** [comment]
> I'm not 100% sure, but I think stopping the generation has no effect on the usage.

Right, I didn't knew stopping would not help with cost. Anyway it still helps with time and energy usage. But when I accidentally hit regenerate, it definitely costs usage as well on top of time and energy. 🤷‍♂️

Indeed the proposed alignment of buttons is just an idea. Anyway, having a button that changes functionality and have destructive and resource consumption effect is arguable from UX perspective. Another solution could be to require regenerate response button to be pressed a bit longer or double, old require holding a button to activate...

Keeping the previous response indeed alleviate the issue with a destructive action creeping suddenly under the mouse, but would still mean unintentional processing. Afaics inferring costs significant energy, so if accidental regeneration can be avoided, it is a good point for the environment as well. I understand that the costs associated with an accidental click is negligible, but the CO2 footprint can be a reason to improve it too.

Thank you for considering this!

**Comment by carlrobertoh** [comment]
Thank you for sharing your ideas!

I appreciate your input and will definitely consider them to improve the extension. 
Furthermore, having some kind of UI design would be really helpful here.

**Comment by carlrobertoh** [comment]
@BenceSzalai 
I have placed the buttons in a different locations, which should now prevent accidental clicks.
<img width="697" alt="Screenshot 2023-06-06 at 00 21 31" src="https://github.com/carlrobertoh/CodeGPT/assets/15891408/14121dc8-c94a-404a-83c1-3a72cc351e03">

Let me know what you think or if there's room for improvement.
Thank you!

**Comment by BenceSzalai** [comment]
Awesome, thank you!
